### ISSUE TITLE
will it work on windows?

### ISSUE THREAD

**Issue by Sandy4321** [guillermo-navas-palencia/optbinning#1]
great code 
thanks
will it work on windows?

**Comment by guillermo-navas-palencia** [comment]
Hi Sandy,

I have tested it on Windows. It should work. Let me know if you have any problems.

**Comment by guillermo-navas-palencia** [comment]
Tested for python 3.6 and 3.7 on Windows. Check [Travis CI](https://travis-ci.com/guillermo-navas-palencia/optbinning).
