### ISSUE TITLE
`metric_missing` and `metric_special` defined for fitting, but not for predictions or scorecard points

### ISSUE THREAD

**Issue by KasperDeBlieck** [guillermo-navas-palencia/optbinning#100]
Hi,

When transforming the data for a scorecard, `metric_special` and `metric_missing` can be defined to specify replace the values in the missing or special bin with either the empirical weight of evidence, or an integer. By default, the metric will be 0.

When fitting a model with a metric different from 0, this is not taken into account in the score calculation. Here, the WoE will be used in each situation.

When predicting a fitted model, the transform method will be called with the default arguments for  `metric_special` and `metric_missing` (which is 0), which might again lead to wrong predictions for the missing or special bin.

Proposed solution in the `Scorecard` class (scorecard/scorecard.py):
* Adjust the scorecard points calculation in the `_fit` method.
* `metric_special` and `metric_missing` class properties that are being set in the `_fit` method, and use these class attributes when predicting a scorecard.

https://github.com/guillermo-navas-palencia/optbinning/pull/101

Kind regards,
Kasper

**Comment by KasperDeBlieck** [comment]
https://github.com/guillermo-navas-palencia/optbinning/pull/101

**Comment by guillermo-navas-palencia** [comment]
Thank you. I close this issue.
