### ISSUE TITLE
Error in importing optbinning in Pandas UDF on a Windows platform

### ISSUE THREAD

**Issue by LBonfi** [guillermo-navas-palencia/optbinning#110]
Hi, 

I am facing issues while trying to import optbinning within a Grouped Map Pandas UDF on a Windows platform as shown in a very simple example below, and it returns the generic error message "Python worker exited unexpectedly (crashed)".
``` 
import optbinning # it works fine outside Pandas UDF

## Example with pandas UDF:
pdf_test = pd.DataFrame(
    {
        "prova": np.arange(100),
        "target": np.random.choice([0, 1], 100),
        "g": np.zeros(100),
    }
)
df_test = spark.createDataFrame(pdf_test)

udf_schema = [StructField("a", StringType(), True)]
udf_schema = StructType(udf_schema)

   
@pandas_udf(udf_schema, PandasUDFType.GROUPED_MAP)
def test_pandas_udf(pdf):
    try:
        import optbinning
        return pd.DataFrame({"a":["OK"]})
    except e:
        return pd.DataFrame({"a":[str(e)]})

df_test.groupby("g").apply(test_pandas_udf).toPandas()
```

Outside the pandas UDF the import runs successfully and I can use the functions of the library without any issue.
 
I am currently working in an environment with the following packages: 
- python 3.7
- pyarrow 0.11.1
- pyspark 2.4.7
- optbinning 0.11.0

Platform: Windows-10-10.0.19041-SP0

I also tried running the script in a different environment with more recent versions of the above packages and it threw the same error message. 
On the other hand, the same script runs smoothly on a MacOS without any error.

I would really appreciate your help.
Thanks

**Comment by guillermo-navas-palencia** [comment]
Hi @LBonfi,

Unfortunately, I do not have a Windows machine to reproduce this error. Perhaps you might not need Spark for binning, if you explain what you are trying to do, I might point you out to some of the functionalities targeted for large datasets.

**Comment by guillermo-navas-palencia** [comment]
Please re-open if you can provide additional information.

**Comment by LBonfi** [comment]
Hi @guillermo-navas-palencia, 

we found out that the problem with the import of the library within the pandas udf was caused by two other libraries that were automatically imported along with optbinning, which are not generally supported by pandas udfs:

- matplotlib.pyplot
- dill

It was sufficient to temporarily remove the import of these libraries to run our code.
Thanks for your support
