### ISSUE TITLE
Scorecard does not work with cross_val_score/predict

### ISSUE THREAD

**Issue by onacrame** [guillermo-navas-palencia/optbinning#111]
The Scorecard object does not currently work with sklearn's cross_val_score or cross_val_predict.  Being able to generate cross-validated metrics/predictions is helpful to determine the robustness of the model to the different data splits.

**Comment by guillermo-navas-palencia** [comment]
Hi @onacrame,

Indeed, the Scorecard object does not accept two arguments (X, y) but only a dataframe that must include the target column. Note that the scorecard is not mean to be used as an estimator. For your purposes, you can use something like this:

```python
from optbinning import BinningProcess

from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline

data = load_breast_cancer()

variable_names = data.feature_names
X = data.data
y = data.target

binning_process = BinningProcess(variable_names)

clf = Pipeline(steps=[('binning_process', binning_process),
                      ('regressor', LogisticRegression())])

cross_val_score(estimator=clf, X=X, y=y, cv=3, scoring='f1')
```

**Comment by guillermo-navas-palencia** [comment]
I might rethink the API to match the BinningProcess fit method. Thanks for the suggestion.

**Comment by onacrame** [comment]
Thanks for your response.  In my use case the underlying LogisticRegression instance can show a high variance when run across difference cuts of data so some version of the scorecard that constructed off cross validated predictions or model instances might be useful.  

There are probably many ways to do this and it may be the case that it may be better to roll one’s own estimator to work with Scorecard rather than build it directly into the package, but just wanted to highlight the use case.

**Comment by guillermo-navas-palencia** [comment]
Hi @onacrame,

I changed the API for the Scorecard and ScorecardMonitoring class as suggested. This change is in master and will be part of the next release 0.12.0.

Thank you for your contribution.

**Comment by onacrame** [comment]
Awesome thanks
