### ISSUE TITLE
monotonic_trend creating only one bin

### ISSUE THREAD

**Issue by mkennealy** [guillermo-navas-palencia/optbinning#112]
Hello, 

Firstly, thank you for all the hard work that went into this package, its fantastic.

I'm working from the following tutorial: 

http://gnpalencia.org/optbinning/tutorials/tutorial_binning_process_FICO_update_binning.html

When I instantiate a Scorecard object based on the BinningProcess object created in this tutorial, the binning_fit_params don't appear to be applying correctly. Specifically, if I reverse the monotonic_trend of a variable, only one bin ([-inf,inf)) is created. Setting min_n_bins to a higher number still only results in one bin.

For example, if I change the monotonic_trend of the variable "ExternalRiskEstimate" from "descending" to "ascending" it results in only the [-inf,inf) bin, even if I set min_n_bins to 10 (see image below) (binning_fit_params and scorecard code are shown at the bottom for reference)

![image](https://user-images.githubusercontent.com/74072437/122937134-a2208880-d369-11eb-9a3c-a64d81b5c51c.png)

For comparison, these are the bins when mononotonic_trend is "descending":

![image](https://user-images.githubusercontent.com/74072437/122937044-8fa64f00-d369-11eb-96cc-8d0a52fcab31.png)

My question is: how I can change the monotonic_trend from descending to ascending for a given variable, and still have multiple bins for this variable (rather than a single [-inf,inf) bin)?

A more general question: Can all of the parameters in optbinning.OptimalBinning be applied to a specific variable in BinningProcess within binning_fit_params?

Many thanks in advance.

The code I am using for the scorecard is as follows:
----------------------------------------
X_train_with_target = X_train.copy()
X_train_with_target["RiskPerformance"] = y_train

estimator = LogisticRegression(max_iter=500, random_state=1993) 

scaling_method = "min_max"
scaling_method_data = {"min": 0, "max": 100}

scorecard = Scorecard(
    target='RiskPerformance',
    binning_process=binning_process,
    estimator=estimator,
    scaling_method=scaling_method,
    scaling_method_params=scaling_method_data,
    intercept_based=False,
    reverse_scorecard=True,
)

scorecard.fit(X_train_with_target)
scorecard_summary = scorecard.table(style="detailed").round(3)

--------------------------------------
My binning_fit_params are set as follows:

binning_fit_params = {
    **"ExternalRiskEstimate": {"monotonic_trend": "ascending","min_n_bins":10},**
    "MSinceOldestTradeOpen": {"monotonic_trend": "descending"},
    "MSinceMostRecentTradeOpen": {"monotonic_trend": "descending"},
    "AverageMInFile": {"monotonic_trend": "descending"},
    "NumSatisfactoryTrades": {"monotonic_trend": "descending"},
    "NumTrades60Ever2DerogPubRec": {"monotonic_trend": "ascending"},
    "NumTrades90Ever2DerogPubRec": {"monotonic_trend": "ascending"},
    "PercentTradesNeverDelq": {"monotonic_trend": "descending"},
    "MSinceMostRecentDelq": {"monotonic_trend": "descending"},
    "NumTradesOpeninLast12M": {"monotonic_trend": "ascending"},
    "MSinceMostRecentInqexcl7days": {"monotonic_trend": "descending"},
    "NumInqLast6M": {"monotonic_trend": "ascending"},
    "NumInqLast6Mexcl7days": {"monotonic_trend": "ascending"},
    "NetFractionRevolvingBurden": {"monotonic_trend": "ascending"},
    "NetFractionInstallBurden": {"monotonic_trend": "ascending"},
    "NumBank2NatlTradesWHighUtilization": {"monotonic_trend": "ascending"}
}

**Comment by guillermo-navas-palencia** [comment]
Hi @mkennealy,

The fitting parameters to feature ExternalRiskEstimate returns only one bin because the result is infeasible, i.e., it is not possible to return 10 bins if the monotonicity trend is set to "ascending". To see that use ``scorecard.binning_process_.summary()``

![image](https://user-images.githubusercontent.com/40094942/122965605-aad48700-d388-11eb-9f9b-dbfc81ba565e.png)

All parameters provided using ``binning_fit_params`` apply. Finally, there is an option to ignore monotonicity; just use ``monotonic_trend``: None. If you do that:

![image](https://user-images.githubusercontent.com/40094942/122966254-64335c80-d389-11eb-9724-80f7bc69c1ef.png)

This shows a sort of peak, but an overall descending trend. Let me know if you still have any doubt.

Guillermo

**Comment by guillermo-navas-palencia** [comment]
I close this issue. Feel free to re-open it if any extra clarification is needed.
