### ISSUE TITLE
unexpected keyword argument 'target'

### ISSUE THREAD

**Issue by billy-odera** [guillermo-navas-palencia/optbinning#117]
I am building the scorecard model but when i try to instantiate I get the error below

```
target = "RISK_COULUMN"
y = train[target].values

scorecard_full = Scorecard(target=target,binning_process=binning_process,estimator=lr,scaling_method=scaling_method,scaling_method_params=scaling_method_data,intercept_based=False,
                           reverse_scorecard=False)
```
`TypeError: __init__() got an unexpected keyword argument 'target'`

**Comment by guillermo-navas-palencia** [comment]
I assume you are using the master branch. See https://github.com/guillermo-navas-palencia/optbinning/issues/111. You can still use the previous API using version 0.11.0 or previous ones.
