### ISSUE TITLE
Inlusive/Exclusive bin edges

### ISSUE THREAD

**Issue by mkennealy** [guillermo-navas-palencia/optbinning#119]
Hello,

It seems there is an issue with the inclusivity/exclusivity of the ranges for the bins.

I've tested this on the example dataset below:

[example_data.xlsx](https://github.com/guillermo-navas-palencia/optbinning/files/6822522/example_data.xlsx)

See below for the output when I perform binning on this variable:

![image](https://user-images.githubusercontent.com/74072437/125777522-d16c28d6-9bd6-429f-82df-20bbcf1b581b.png)

Conventional notation states that square brackets mean that end is **inclusive** and contains the listed element, while parenthesis/curly brackets mean that end is **exclusive** and doesn't contain the listed element. As such, the [-inf, 0.02) bin, should not contain the value 0.02, however the bin count is the same as the number of rows with value <=0.02. 

I have found this problematic for variables where the bin [-inf, 0.00) includes both zero and negative values, instead of only negative values.

**Comment by guillermo-navas-palencia** [comment]
Hi @mkennealy,

Your comment is incorrect. The binning table has a parameter called "show_digits", by default set to 2. The split points in the binning table are rounded to two decimal places. The actual split points can be retrieved via ```optb.splits```

![image](https://user-images.githubusercontent.com/40094942/126058169-2a127457-0a43-404c-bb47-c6e830bdb76c.png)

Please read the documentation: http://gnpalencia.org/optbinning/binning_tables.html
![image](https://user-images.githubusercontent.com/40094942/126058015-e9795be3-d05d-4540-89d9-b79c9444bb87.png)

**Comment by mkennealy** [comment]
Thank you for your response - that clarifies the issue
