### ISSUE TITLE
Question about scorecard points and optimal trends

### ISSUE THREAD

**Issue by mkennealy** [guillermo-navas-palencia/optbinning#120]
Hello, 

I have the following questions:

1. How exactly are the scorecard points calculated in the case of a binary target? Is it calculated as WoE * coefficient (as mentioned in the final post in the thread https://github.com/guillermo-navas-palencia/optbinning/issues/27) and then converted into points based on the min and max (assuming scaling_method is set to "min max")

2.  When I perform optimal binning on an individual variable with respect to the target, and analyse its binning table (optb.binning_table.analysis()), it returns the monotonic trend. However, this monotonic trend doesn't always match the points given to each bin in the scorecard summary. i.e. the monotonic trend will be "ascending" but the scorecard points appear descending. Is this because the monotonic trend is based on the event rate, while the scorecard points are based on the WoE*coefficient? It is hard to justify using points that go in the opposite direction to the event rate i.e. higher event rate but lower number of points.

3. I noticed the Special bin is given the same number of scorecard points for every variable, regardless of what the count in the bin is (see example below). I would have expected it would be treated similarly to the Missing bin which differs in points for each variable.

![image](https://user-images.githubusercontent.com/74072437/126623338-8bb1cf54-380d-498a-b820-a84dd799226d.png)

Many thanks in advance.

**Comment by guillermo-navas-palencia** [comment]
Hi @mkennealy

1. Yes, correct.
2. Yes, correct. WoE is inversely related to the event rate.
3. By default, missing values are transformed to 0. To apply the empirical transformation you have to set metric_special="empirical" and pass this information via the parameter binning_transform_params of the BinningProcess class.

**Comment by brungrujiphaisal** [comment]
Hi @guillermo-navas-palencia 
I would like to confirm the formula used to calculate the points by multiplying the WoE and the coefficient of the logistic regression. However, it does not yield the expected result. For example, in the first bin, WoE = 0.842, and the coefficient = -0.482, which should give a result of -0.405844. I am wondering what additional steps are taken to arrive at the exact figure of -1.196?
Thank you in advance.
