### ISSUE TITLE
Spark Parrallel

### ISSUE THREAD

**Issue by cfkstat** [guillermo-navas-palencia/optbinning#121]
At work now, I have a data box of 300000 times 300000 stored in Hive. Considering the calculation of variables WOE, IV and PSI, the parallel calculation of Pyspark row is relatively simple, but the parallel calculation based on columns seems to be very difficult. Optbinning has implemented the parallel calculation of single variable row based Spark version. Is there a reference to the implementation based on columns？

**Comment by guillermo-navas-palencia** [comment]
Hi @cfkstat,

The class BinningProcess can handle large datasets by loading one column at a time. I suppose this could be efficiently parallelized. See http://gnpalencia.org/optbinning/binning_process.html#optbinning.BinningProcess.fit_disk. I have never tried to apply binning for such large datasets.
