### ISSUE TITLE
Adding a variable that doesn't meet selection criteria

### ISSUE THREAD

**Issue by onacrame** [guillermo-navas-palencia/optbinning#123]
I may want to retain a variable or variables that don't meet the IV cutoff criteria purely because the business expects to see the variable in the model.  Can I force binning process to retain a variable based solely on a list of column names to keep?

**Comment by guillermo-navas-palencia** [comment]
This would be an interesting addition. In the meantime, a workaround is to instantiate a new binning process using the method ``fit_from_dict``: http://gnpalencia.org/optbinning/binning_process.html#optbinning.BinningProcess.fit_from_dict

**Comment by guillermo-navas-palencia** [comment]
A new option ``fixed_variables`` has been added to the ``BinningProcess`` class. This is part of master, and will be included in the release 0.12.1.
