### ISSUE TITLE
Allow use of sample weight in BinningProcess

### ISSUE THREAD

**Issue by HFulcher** [guillermo-navas-palencia/optbinning#124]
Looking at the `fit` method of `BinningProcess` there is no way to provide a sample weight to the underlying `OptimalBinning` class. It would be useful to be able to pass the sample weight through `BinningProcess` rather than having to call `OptimalBinning` individually.

**Comment by guillermo-navas-palencia** [comment]
I agree. However, the binning process was meant to be generic (it can handle binary, continuous, and multiclass target), but only the OptimalBinning class for binary target support the parameter sample_weight during the fit. It will be added with None as the default value, as in the OptimalBinning class.

**Comment by HFulcher** [comment]
That's great, thanks very much. I appreciate the goal of keeping things generic.

**Comment by kitchenseg** [comment]
> I agree. However, the binning process was meant to be generic (it can handle binary, continuous, and multiclass target), but only the OptimalBinning class for binary target support the parameter sample_weight during the fit. It will be added with None as the default value, as in the OptimalBinning class.

Why is it that `sample_weight` or observation weight cannot be used in the `ContinuousOptimalBinning` class? Many problems involve targets that are ratios and a best practice is to use the denominator as an observation weight, so it would be highly desirable to be able to use weights even for continuous binning.

**Comment by guillermo-navas-palencia** [comment]
@kitchenseg. Generally, sample weights are associated with classification problems with multiple classes. I think I understand what you mean, but could you provide an example of the desired output (binning table, for instance).

**Comment by guillermo-navas-palencia** [comment]
Never mind, it is rather easy. I will include it as part of the next release 0.12.1.

**Comment by guillermo-navas-palencia** [comment]
I close this issue since ``sample_weight`` is now supported for ``BinningProcess`` with a binary target (master branch). I will open a new one to use sample weights with a continuous target.
