### ISSUE TITLE
MDLP not working with iris dataset

### ISSUE THREAD

**Issue by marcdhansen** [guillermo-navas-palencia/optbinning#125]
Hi, I modified the test_mdlp.py code in the repository to work with the iris dataset, but no splits are being created.

I'm attaching a copy of the modified test code with the .py extension changed to .txt so that it will upload:
[test_mdlp.txt](https://github.com/guillermo-navas-palencia/optbinning/files/6979186/test_mdlp.txt)

**Comment by guillermo-navas-palencia** [comment]
Hi @marcdhansen,

The MDLP algorithm only works with a binary target. The iris dataset has a multi-class target. You can use the ``MulticlassOptimalBinning`` class instead.

http://gnpalencia.org/optbinning/binning_multiclass.html
http://gnpalencia.org/optbinning/tutorials/tutorial_multiclass.html
