### ISSUE TITLE
Monotonic Trend - enforcing trend doesn't seem to match event rate

### ISSUE THREAD

**Issue by rohandholakia1** [guillermo-navas-palencia/optbinning#129]
Hi,

I am having an issue regarding setting the monotonic trend. For a specific variable, the trend is set to descending as that would be the expected trend which also ties out with how the event rate works. However, after setting this trend through the logic below being passed into binning_fit_params, the trend being applied to the points is ascending rather than descending.

The below paragraphs comes from a tutorial on OptBinning which mentions that the trend applied is based on event rate which is what is causing some confusion on my side.

http://gnpalencia.org/optbinning/tutorials/tutorial_multiclass.html

Event rate monotonicity
The monotonic_trend option permits forcing a monotonic trend to the event rate curve of each class. The default setting “auto” should be the preferred option, however, some business constraints might require to impose different trends. The default setting “auto” chooses the monotonic trend most likely to maximize the information value from the options “ascending”, “descending”, “peak” and “valley” for each class using a machine-learning-based classifier.

The below is how the trend is being set :
    
```
binning_fit_params = {
                                  'Variable': {'monotonic_trend': 'descending'} 
                                   }
```

This binning_fit_params then gets passed into binning_process as below :

    binning_process = BinningProcess(
        categorical_variables=cat_cols,
        variable_names=list_features,
        selection_criteria=selection_criteria,
        binning_fit_params = binning_fit_params)

This is then passed to Scorecard as below :

    # Instatiate and fit Scorecard
    scorecard = Scorecard(
        target='Target',
        binning_process=binning_process,
        estimator=estimator,
        scaling_method=scaling_method,
        scaling_method_params=scaling_method_data,
        intercept_based=False,
        reverse_scorecard=True
    )

The table below shows the event rate going in a descending trend but the trend based on the points is ascending.

![image](https://user-images.githubusercontent.com/51082733/132231410-8d766ebd-fc76-41bc-94fd-8d77530db79e.png)

Would be much appreciated for your guidance on this

Thanks,
Rohan

**Comment by guillermo-navas-palencia** [comment]
Hi @rohandholakia1,

I do not see the problem. The binning table shows a descending event rate, as expected. Make use you are using the right option when plotting (``metric="event_rate"``, by default is set to ``metric="woe"``).

**Comment by guillermo-navas-palencia** [comment]
I close it. Please, re-open if anything is still unclear.
