### ISSUE TITLE
Can not Pickle OptBinning Object 

### ISSUE THREAD

**Issue by apatange-source** [guillermo-navas-palencia/optbinning#133]
Whenever I try to Pickle and OptBinning object I get this error. I looked at issue #77. It seemed similar but I am still getting the same error. I'm running python 3.8 with OptBinning 0.12.0

![image](https://user-images.githubusercontent.com/83966389/133741572-bfd67408-3288-4856-8da6-cc560b8b0edc.png)

**Comment by guillermo-navas-palencia** [comment]
Hi @apatange-source. Could you try with dill instead? The methods `save` in OptBinning use this library. See for instance:
* https://github.com/guillermo-navas-palencia/optbinning/blob/master/optbinning/scorecard/scorecard.py#L445
* https://github.com/guillermo-navas-palencia/optbinning/blob/master/optbinning/binning/binning_process.py#L326

**Comment by apatange-source** [comment]
> Hi @apatange-source. Could you try with dill instead? The methods `save` in OptBinning use this library. See for instance:
> 
>     * https://github.com/guillermo-navas-palencia/optbinning/blob/master/optbinning/scorecard/scorecard.py#L445
> 
>     * https://github.com/guillermo-navas-palencia/optbinning/blob/master/optbinning/binning/binning_process.py#L326

Hello! I have gone through the scorecard module. But for my project, it is of the utmost importance to use pickle instead of dill for serialization. Is there a way to make it work with pickle instead of dill?

**Comment by guillermo-navas-palencia** [comment]
Could you try:

```python

optb._optimizer = None
optb._class_logger = None
optb._logger = None
```
before pickle?

**Comment by apatange-source** [comment]
Yes, this is working. Thank you very much @guillermo-navas-palencia :D

**Comment by guillermo-navas-palencia** [comment]
Hi @apatange-source,

If you try the new release 0.12.2, the above modifications should not be needed. Let me know.

**Comment by apatange-source** [comment]
Yep working without the changes now! Thanks @guillermo-navas-palencia
