### ISSUE TITLE
OptimalBinning2D doesn't support categorical variables

### ISSUE THREAD

**Issue by mikkel92** [guillermo-navas-palencia/optbinning#135]
The functionality is there for 1D and should work for 2D as well.

**Comment by guillermo-navas-palencia** [comment]
Hi @mikkel92,

Yes, it should and will be part of future releases.

**Comment by mikkel92** [comment]
Thanks a lot for the fast reply. 
Looking forward to the feature!

All the best - Your fans from Risika

**Comment by guillermo-navas-palencia** [comment]
BTW, do you have any specific requirement or want to share possible applications that might have in mind?

**Comment by mikkel92** [comment]
Nothing other than we have a dataset with a bunch of numerical and categorical variables. It seems like we can make a better model by binning the features in 2D, and it would just be nice to have that option for categorical features as well as numerical.
