### ISSUE TITLE
RuntimeError: The classifier does not expose "coef_" attribute.

### ISSUE THREAD

**Issue by karakastarik** [guillermo-navas-palencia/optbinning#136]
Hi, thanks for this amazing package. As i can understand, the algorithm we use has to coef_ attribute (Logistic Regression, linear models) for Scorecard module. So, we can't use ensemble models like GradientBoostingClassifier or RandomForestClassifier, right? Maybe we can work on adding such algorithms to the scorecard module, i would be happy to help.

**Comment by guillermo-navas-palencia** [comment]
Hi @karakastarik,

A scorecard requires coefficients. However, you can combine the binning process with an estimator by creating your own pipeline. See this example:  http://gnpalencia.org/optbinning/tutorials/tutorial_binning_process_sklearn_pipeline.html

**Comment by karakastarik** [comment]
Okay @guillermo-navas-palencia thank you so much!
