### ISSUE TITLE
Bug in binning process/scorecard.score when adding binning_transform_params

### ISSUE THREAD

**Issue by mik3githubber** [guillermo-navas-palencia/optbinning#140]
Using the FICO example, if I add the following:

```
binning_transform_params = {
        'ExternalRiskEstimate': {'metric' : 'woe'}}
```
And then fit the following binning process instance:

```
binning_process = BinningProcess(variable_names, special_codes=special_codes,
                                 selection_criteria=selection_criteria,binning_transform_params=binning_transform_params)
```

Then the scores provided by scorecard.score are all clustered around a single number as per below: 

![huhuh](https://user-images.githubusercontent.com/62071547/139867262-425b656d-4511-4fc7-89f7-67840915115c.png)

 As opposed to what's shown in the online example

**Comment by guillermo-navas-palencia** [comment]
Hi @mik3githubber,

I will look into this. I assume the online example you are referencing is: http://gnpalencia.org/optbinning/tutorials/tutorial_scorecard_binary_target.html

**Comment by mik3githubber** [comment]
Yes correct that example.  Suspect that it has something to do with the transform method of binning processes using a default metric of “indices” but the binning_transform_params supplying a different metric.

**Comment by guillermo-navas-palencia** [comment]
Yes, I think you are right. I do not see a simple fix except raising an exception during fit if any feature in binning_process includes the key "metric".

**Comment by mik3githubber** [comment]
Understood, I'll refrain from using the binning transform params in that case.
