### ISSUE TITLE
Binning process/transform/metric_special (float or str (default=0))

### ISSUE THREAD

**Issue by xueyizhiyong-UUU** [guillermo-navas-palencia/optbinning#141]
Hello, I think the missing item should be default=empirical, otherwise it will be 0 by default. It is very misleading after the data is divided into boxes

**Comment by guillermo-navas-palencia** [comment]
Hi @xueyizhiyong-UUU. I disagree. If empirical is the default option, and empirical produces NaN, you cannot compute divergence measures such as IV.
