### ISSUE TITLE
Monotonic trend over a time variable

### ISSUE THREAD

**Issue by dblop** [guillermo-navas-palencia/optbinning#142]
I'm interested in a binning process that applies the monotonic trend over all values of a time period. Meaning it's not only monotonic in general, but it guarantees the monotonic constraint over all groups of a different variable (time). A similar approach for minimum bin size would be interesting, now that I think of it. Is this possible with the library?

**Comment by guillermo-navas-palencia** [comment]
Hi @dblop,

Do you mean something like this:
- http://gnpalencia.org/optbinning/tutorials/tutorial_binary_under_uncertainty.html
- http://gnpalencia.org/optbinning/binning_scenarios.html

Where your scenarios are the data for each time period.

**Comment by dblop** [comment]
Thanks! I think it fits what I need. FYI if SBOptimalBinning supported some variation of auto monotonic_trend & BinningProcess these would be very nice features.

**Comment by guillermo-navas-palencia** [comment]
The auto monotonic_trend parameter would be interesting, but it will require a consensus trend over all periods. Extending the BinningProcess to handle SBOptimalBinning should not be too difficult. I do not have much time at this moment, so PRs are welcome.
