### ISSUE TITLE
Adding feature: return set of solutions that is less reasonable than the best solution

### ISSUE THREAD

**Issue by nic9lif3** [guillermo-navas-palencia/optbinning#15]
Hi @guillermo-navas-palencia.
Thank you for this great project. It's very helpful for my work. I wonder if the model returns some other less reasonable solutions. In some circumstances, some businesses need additional conditions that cannot be indicated in the model's parameters. So I think the best way is filtering that conditions from the less reasonable solutions set to find suitable ones. That's why I would like to ask to add the feature in the next version.
Thanks in advance.

**Comment by guillermo-navas-palencia** [comment]
Hi @nic9lif3,

Thanks for your comment, glad you find it helpful. It is possible to disable practicably all constraints to allow/force some solutions. Here a few examples:
- Monotonicity: use parameter ``monotonic_trend=None`` to avoid imposing any trend.
- Use parameter ``user_splits``: http://gnpalencia.org/optbinning/tutorials/tutorial_binary.html#User-defined-split-points.
- Decrease/increase ``max_n_prebins`` and ``min_prebin_size``. 
- The default value for other parameters is None, therefore there is quite a freedom to obtain other solutions.

Perhaps, you could provide a complete example to see whether it is possible to obtain your desired results with the currently available options. Nonetheless, let me know in case you would like to incorporate new types of constraints to the formulation.

**Comment by nic9lif3** [comment]
Hi @guillermo-navas-palencia,
Thanks for your answer but it is not like what I express. Sometime the configuration of the model (min bin size, max bin size, trend...) is what we need but it isn't what all we need. Example: we don't want put value A in the same bin with value B, but your model don't how configuration to ignore it. There are many unknown conditions and I think you cannot cover all of this. So to make this model is more adaptive, you can return a set of splits, order by IV value. From that, we can choose other solution that satisfy addition conditions and it's IV is highest as model can solve.

**Comment by guillermo-navas-palencia** [comment]
Hi @nic9lif3,
Thanks for the clarification; I think I understand it now. You are asking for the set of all feasible solutions ordered in terms of the IV (objective function). This should not be difficult, but I need to study how to expose this option to the user. **In the meantime**, that particular example is handleable if the user provides a list of user splits to be fixed. Example:
- ``user_splits=[sA, sB, sC, sD]``
- ``user_splits_fixed=[True, True, False, False]``

In this way, bin A: [-Inf, sA) and bin B:[sA, sB) will never be merged. If you find this option might be helpful, it is fairly quick to implement.

**Comment by nic9lif3** [comment]
Thanks @guillermo-navas-palencia for advise.

**Comment by guillermo-navas-palencia** [comment]
HI @nic9lif3,

You can now test the ``user_splits_fixed`` parameter in the new release 0.5.0.

Thanks!
