### ISSUE TITLE
Summary() Results Do Not Update After Using 'update_binned_variable' Method

### ISSUE THREAD

**Issue by tubbytim** [guillermo-navas-palencia/optbinning#151]
Hey,

I am using your package to try an create a dynamic binning web app where the user can choose variables, update splits, add new splits etc and see the results in real time and I have come across an issue where after you use the 'update_binned_variable' method and change the splits of a variable, the statistics shown in the Summary() results do not reflect the new splits but rather the original splits (Please see below for an example). In the example I have changed the splits for the 'Mean Texture' variable which drops the IV down to 0.92 but when I run the Summary table it still shows the original statistic.

I am wondering if I am doing something wrong or if these is a genuine bug that could be fixed?

Thanks very much!

![Optbinning_Summary_issue](https://user-images.githubusercontent.com/63002746/154587242-47caea7f-3d02-414c-bf4c-564f38ce1f28.PNG)

**Comment by guillermo-navas-palencia** [comment]
Hi @tubbytim,

You are right. The summary information is not updated after updating binning variables. I will look into this. Thanks for noticing.

**Comment by joaoOarthur** [comment]
I have exactly the same problem, with last version installed

<img width="266" alt="image" src="https://user-images.githubusercontent.com/44378399/159946231-4336e927-2e86-4b54-8ce9-dd50261ffeb2.png">

**Comment by guillermo-navas-palencia** [comment]
Hi @joaoOarthur,

Could you please provide a reproducible example?

**Comment by joaoOarthur** [comment]
Here it goes:

```
import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression
from optbinning import OptimalBinning, BinningProcess, Scorecard

# create dataset
df = pd.DataFrame({'feature1': np.random.normal(0, 1, 10000),
                   'feature2': np.random.normal(10, 2, 10000),
                   'target': np.random.randint(2, size=10000)})

# split X,y
X = df.drop(columns='target')
y = df['target']

# fit binning process
selected_features = ['feature1', 'feature2']

binning_process = BinningProcess(selected_features)
binning_process.fit(X, y)

# check binning table for feature1
binning_process.get_binned_variable('feature1').binning_table.build()
```
<img width="563" alt="image" src="https://user-images.githubusercontent.com/44378399/160144080-240d4aa0-d9fa-4703-897b-c36965165dcf.png">

```
# update feature1 bins manually
optb = OptimalBinning(name='feature1', user_splits=[-1.11, 1])
optb.fit(X['feature1'], y)

binning_process.update_binned_variable(name='feature1', optb=optb)

# check if feature1 were updated
binning_process.get_binned_variable('feature1').binning_table.build()

```
<img width="521" alt="image" src="https://user-images.githubusercontent.com/44378399/160144256-5780e8de-9e46-4093-aa56-636975010c03.png">

```
# estimator
estimator = LogisticRegression(solver="lbfgs")

# fit scorecard
scorecard = Scorecard(binning_process=binning_process,
                      estimator=estimator, scaling_method="min_max",
                      scaling_method_params={"min": 0, "max": 1000})

scorecard.fit(X, y)


scorecard.table(style="summary")

```

<img width="216" alt="image" src="https://user-images.githubusercontent.com/44378399/160144339-7680e332-6df9-493a-9ab3-19afc6203b73.png">

As you can see in scorecard table, `feature1` kept the default binning. (even when scoring, so it does not look like a problem in scorecard.table() only)

**Comment by joaoOarthur** [comment]
@guillermo-navas-palencia I found out what may be the problem:

in method _fit from Scorecard we have:

```
X_t = self.binning_process_.fit_transform(
            X[self.binning_process.variable_names], y, sample_weight, metric,
            metric_special, metric_missing, show_digits, check_input)
```

when computing score, we fit binning_process again, so it goes back to original configuration.

I just cloned the repository and changed it to use the binning_process to create a dict of OptimalBinning's, and used `fit_from_dict` method, and it worked. 

```
selected_variables = self.binning_process.get_support(names=True)

        # Create dict of optimal binnins
        optb_dict = {}
        for feature in selected_variables:
            optb_ = self.binning_process.get_binned_variable(feature)
            optb_dict[feature] = optb_

        # Suppress binning process verbosity
        self.binning_process_.set_params(verbose=False)

        # Fit again from dict of optimal binnings
        self.binning_process_.fit_from_dict(optb_dict)

        X_t = self.binning_process_.transform(
            X[self.binning_process.variable_names], metric,
            metric_special, metric_missing, show_digits, check_input)

```

and it worked :D

**Comment by guillermo-navas-palencia** [comment]
Hi @joaoOarthur,

Your solution is suitable for your needs, but I consider it might incur some risks. For example, it assumes that the binning process was fitted with the same data as the scorecard. The parameter ``binning_fit_params`` is the recommended option to pass the user-specified option to a variable:
```python
# binning process
binning_process = BinningProcess(selected_features,
                                 binning_fit_params={'feature1': {"user_splits": [-1.11, 1]}})

# estimator
estimator = LogisticRegression(solver="lbfgs")

# fit scorecard
scorecard = Scorecard(binning_process=binning_process,
                      estimator=estimator, scaling_method="min_max",
                      scaling_method_params={"min": 0, "max": 1000})

scorecard.fit(X, y)
scorecard.table(style="summary")
```
