### ISSUE TITLE
Adding an 'Adjust WoE' Option

### ISSUE THREAD

**Issue by tubbytim** [guillermo-navas-palencia/optbinning#154]
Hey Guillermo, 

Firstly I just want to say that I am really enjoying this package. It is exactly what I was looking for when I was attempting to build Credit Risk scorecards in Python rather than in SAS.

From using the package a lot I have noticed that there have been instances where the user defined splits will fall over due to the fact that a split that has been created will have only a single class in it.

A way we used to fix this was to add a WoE adjustment to the bins that had only 1 class in them. the adjustment factor is a value between 0 and 1 that is added to the number of events and the number of non-events in order to calculate WoE. The new formula to calculate the WOE for these bins would look like the following:

<img src="https://render.githubusercontent.com/render/math?math=WoE_{adjusted} = \frac{\frac{n^{attribute}_{non-event}  \pm adjustment factor}{n^{population}_{non-event}}}{\frac{n^{attribute}_{event}  \pm  adjustment factor}{n^{population}_{event}}}">

I was wondering is this something you would be able to implement or see value in adding to the optbinning class? It would allow the exploration of different bins that contain only one class which may be seen as important to the end user?

Thanks,
Seán

NOTE: The plus/minus in the formula should just be + but I couldn't get Github to do what I wanted.......

**Comment by guillermo-navas-palencia** [comment]
Hi @tubbytim,

I recall this WoE adjustment is used by default in SAS interactive grouping https://documentation.sas.com/doc/en/emref/14.3/p1qzwz7onopjqcn11uc04i18urg7.htm. Adding this functionality is doable, but not sure whether having a final binning table with zero elements in the event and/or nonevent column, but a valid information value is rigorous. I think using the available constraints to specify the minimum number of events/nonevents per bin returns more meaningful results.

Having said so, I am open to considering it if anyone can argue the benefits of this feature.

**Comment by guillermo-navas-palencia** [comment]
Regarding the message thrown when user-defined splits create empty (event or nonevent) bins: I think this is a reasonable approach to avoid modellers creating "fake" binning tables. I am aware that in some situations there are some business constraints in place to force bins. However, forcing bins without backup data does not seem right to me, and I consider it a widely extended bad practice within the credit risk field.
