### ISSUE TITLE
Line2D object has no property metric

### ISSUE THREAD

**Issue by jorgebaez212** [guillermo-navas-palencia/optbinning#155]
Hi, this is an awesome work but I'm facing some issues while trying to plot the binning_table, and I think it could be an issue.
![image](https://user-images.githubusercontent.com/1607099/155321845-d5714a4a-ec0f-406a-b68e-4917e453bd3a.png)

If the metric parameter is removed, the error disappears, but the plot is definitively not is expected:
![image](https://user-images.githubusercontent.com/1607099/155322072-523d0830-8e19-4845-8f74-adcf72386481.png)

From the required libs listed on git, the versions of the libs on the system are:

dill==0.3.4
matplotlib==3.5.1
numpy==3.5.1
ortools==9.2.9972
pandas==1.4.1
ropwr==0.2.0
scikit-learn==1.0.2
scipy==1.8.0
tdigest==0.5.2.2

I also tried with different versions of matplotlib, but just couldn't make it run.

Does this sound like an optbinning issue or could it be something else that I'm missing?

**Comment by guillermo-navas-palencia** [comment]
Hi @jorgebaez212.

The error is simple. You are plotting a binning table (ergo a dataframe) not the actual binning table. These operations cannot be chained. To do so:
```python

optb.binning_table.build()
optb.binning_table.plot()

```
