### ISSUE TITLE
Include non-binned columns in transform dataframe

### ISSUE THREAD

**Issue by VSGAN** [guillermo-navas-palencia/optbinning#156]
First, very impressed.  Great tool you have developed here.  Maybe i missed it but when i try to "carry along" another column defined as index so i can merge the generated binned data to another dataframe later the index column is reset.  Thanks for developing and sharing.  Once again, great tool!

**Comment by guillermo-navas-palencia** [comment]
Hi @VSGAN,

Thanks! The binning process will not consider the Index, only columns. You can add the index to the transformed dataframe afterwards and use it for merging. The transformed dataframe keeps the original ordering.
