### ISSUE TITLE
Question - Interpreting output items - plots, table and metrics

### ISSUE THREAD

**Issue by SSMK-wq** [guillermo-navas-palencia/optbinning#157]
Hi,

Thanks for such a wonderful package. Very useful for non-computer science folks like me to come up with some optimal threshold. else, we have to manually create sub optimal bins based on judgment.

However, may I check with you on the questions below (on interpretation on Quantity field of a product)

Can you help us with step-step explanation on how to interpret the output from optbinning? Like how would you make a decision to split/not split based on the output returned by optbinning?

a) Based on the below output, how do I know whether it is useful to bin these variables or not?

b) What does the metrics indicate? If bin 0 has WoE of `-0.40`, what does it mean? Similarly, if 2nd bin has `WoE of 0.20`, what does it mean?

c) How do I know which bins contributes more to target 1 and which bins contribute to target 0.

d) I already read the tutorial on how to run `optbinning` but I could not find any tutorial on how to interpret the output from `optbinning` especially when there are plots, table and metrics. So, can you please direct me to resource where I can learn with a simple example? please

![image](https://user-images.githubusercontent.com/30723825/156997128-a78b490a-d172-4a6d-a9a9-d4ae8b8a8a82.png)

![image](https://user-images.githubusercontent.com/30723825/156997271-81003840-1128-41a4-87f2-603d9ce88c91.png)

![image](https://user-images.githubusercontent.com/30723825/156997347-7595db19-976c-40b6-8691-9465ce17115a.png)

**Comment by guillermo-navas-palencia** [comment]
Hi @SSMK-wq,

a) A good metric to decide whether the binned variable is useful (it is valuable for the model) is the information value (IV). In this case, the value 0.24946 is reasonably good. There is a rule of thumb about IV, see: 
![image](https://user-images.githubusercontent.com/40094942/159151493-5bd5b816-2926-4174-b407-cbd1068e698e.png)
For a more general discussion about the characteristic of a good binning, take a look at https://arxiv.org/pdf/2001.08025.pdf section 3.3.

b) The Weight of Evidence (WoE) is a divergence measure indicating how different is the ratio of good and bad records in a bin. Note that WoE is inversely related to the event rate. Also, observe that negative values correspond to event rates above the average event rate and vice-versa.

c) The WoE can help you with that. 

d) This tutorial seems self-explanatory to me: http://gnpalencia.org/optbinning/tutorials/tutorial_binary.html#The-binning-table
