### ISSUE TITLE
Optbinning 2d with categorical variable

### ISSUE THREAD

**Issue by nic9lif3** [guillermo-navas-palencia/optbinning#166]
Hi @guillermo-navas-palencia 

I wonder if binning 2d function can handle categorical variables. I see Optbinning has parameters for dtype_x and dtype_y but it only allow numeric. Will it support categorical or just nothing with this?

Thanks

**Comment by guillermo-navas-palencia** [comment]
Hi @nic9lif3,

At this moment, binning 2d can only handle numeric data. I plan to develop this functionality for releases 0.16.0-0.17.0. This is not particularly easy, and it might take a few months.

**Comment by nic9lif3** [comment]
hi @guillermo-navas-palencia ,

It sounds great. 

Another problem with binning 2d is it treats missing or special_code of both columns into a bin.
Maybe you consider separating this. For example, the null value of column2 between the range value of column1 is different with a column2 null value in another range of column1. So they should have their own WOE.

**Comment by guillermo-navas-palencia** [comment]
Hi @nic9lif3,

I agree that separating missing and special bins would be a good addition. However, I find that implementing the binning 2d with categorical variables first would be more relevant.
