### ISSUE TITLE
Optimal binning without target

### ISSUE THREAD

**Issue by SSMK-wq** [guillermo-navas-palencia/optbinning#167]
Hi, 

I have a continuous variable such as quantity but there is no target variable. It is just a 1D variable and I would like to bin it.

Can Optbinning help discretize the 1D variable?

Or this package can only bin variables which have a corresponding target value?

**Comment by guillermo-navas-palencia** [comment]
Hi @SSMK-wq,

All optbinning function requires a target. To bin variables without a target, I would recommend you to use https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.KBinsDiscretizer.html. This sklearn class is used in OptBinning for prebinning when ``prebinning_method`` is quantile or uniform. See: https://github.com/guillermo-navas-palencia/optbinning/blob/master/optbinning/binning/prebinning.py
