### ISSUE TITLE
Error optbinning 2d

### ISSUE THREAD

**Issue by nic9lif3** [guillermo-navas-palencia/optbinning#168]
hi @guillermo-navas-palencia ,

I try binnning 2d and this error happened. I guest that column contains two much null.

![image](https://user-images.githubusercontent.com/17736568/165914550-66c3339e-31a8-4e89-abdb-94a04ea93006.png)

**Comment by guillermo-navas-palencia** [comment]
Hi @nic9lif3,

Could please provide the data and python code to reproduce this error?

**Comment by nic9lif3** [comment]
HI @guillermo-navas-palencia ,

I just let the information go away. I will update when I get this again.
