### ISSUE TITLE
mismatched between optb.transform(x, metric="indices") and optb.transform(x, metric="bins")

### ISSUE THREAD

**Issue by tranvohuy** [guillermo-navas-palencia/optbinning#169]
Hi @guillermo-navas-palencia,
When transforming values to bins, I found that there is a discrepancy between the two methods   `optb.transform(x, metric="indices") ` and `optb.transform(x, metric="bins")` 
![image](https://user-images.githubusercontent.com/39524209/166719953-9e4a4584-07cd-4b6e-9813-8055fdc794c8.png)
As seen in the pic above, the last 4 values of the array `x` are all `nan`. Hence naturally they belong to bin index = 7 or bin string `Missing`. However, `bin_indices` shows that they belong to bin 0.

I'm not sure if this is intended. Could you please clarify this before I try to debug deeper? 
Thanks, Huy.

**Comment by guillermo-navas-palencia** [comment]
Hi @tranvohuy,

In transform methods, ``metric_missing` is applied except when ``metric="bins"``. By default, ``meric_missing`` is set to zero, hence you see 4 zeroes in ``bin_indices``. To obtain a list of 7s, you need:
```python
bin_indices = optb.transform(x, metric="indices", metric_missing="empirical")
```

The ``metric_missing`` and ``metric_special`` options were devised to provide more flexibility to users, allowing overwriting the empirical information.

**Comment by tranvohuy** [comment]
great. Thanks for the help.
