### ISSUE TITLE
Rounding of bin when displaying a scoring model

### ISSUE THREAD

**Issue by andreykataev** [guillermo-navas-palencia/optbinning#170]
How can configure bins output with greater accuracy than 2 signs?
![image](https://user-images.githubusercontent.com/20297271/169521617-83a5dc44-6d8d-4627-982b-547eb841f832.png)

**Comment by guillermo-navas-palencia** [comment]
Hi @andreykataev,

Good point, this option is available here: http://gnpalencia.org/optbinning/binning_tables.html#optbinning.binning.binning_statistics.BinningTable.build, but it is not propagated to scorecard table. I will add the same option ``show_digits`` in scorecard table.

**Comment by guillermo-navas-palencia** [comment]
The ``.fit()`` method already exposed the option ``show_digits`` but it was only applied to binning transformation. See commit in branch develop: https://github.com/guillermo-navas-palencia/optbinning/commit/aa55821d62c40167f310f6038e5cb7afe5b33706.
