### ISSUE TITLE
Optbinning creating NaN values

### ISSUE THREAD

**Issue by k3ybladewielder** [guillermo-navas-palencia/optbinning#171]
I'm implementing optbinning to create bins with binary target, [just as the documentation](http://gnpalencia.org/optbinning/tutorials/tutorial_binary.html) but some values generated are NaN values. 

I I checked the x values searching errors or Nan value on imputed x on fit, but it correct.

**Comment by guillermo-navas-palencia** [comment]
Hi @k3ybladewielder,

The missing bin is generated in the binning table automatically. If there are no missing values, the count of event and non-event should be zero. Could you please provide a screenshot to confirm?

**Comment by k3ybladewielder** [comment]
the event output of feature age, that have some nan bins

![image](https://user-images.githubusercontent.com/50303964/171521191-67e7eb4f-05d6-4bd1-b534-1fcf71abd319.png)

**Comment by guillermo-navas-palencia** [comment]
I meant the screenshot of the binning table. Could you please provide a reproducible example?
