### ISSUE TITLE
Binning table calculates wrong

### ISSUE THREAD

**Issue by nic9lif3** [guillermo-navas-palencia/optbinning#173]
Hi @guillermo-navas-palencia 

Binning table's result is wrong when calculating event rate and woe of missing value.
Could you recheck if I have any mistakes?

![image](https://user-images.githubusercontent.com/17736568/171578197-b8fb85a4-4793-44af-83cb-d6706b042b0b.png)
[data_full.csv](https://github.com/guillermo-navas-palencia/optbinning/files/8821729/data_full.csv)

**Comment by guillermo-navas-palencia** [comment]
The event rate is set to zero because this is a pure bin (i.e. zero event or non-event records). For calculating woe and IV you cannot have zeros in any column.

**Comment by nic9lif3** [comment]
@guillermo-navas-palencia 

I know the pure bin IV and WOE cannot be calculated, but, I think the event rate can
