### ISSUE TITLE
No split points returned by multiclass binning on iris dataset

### ISSUE THREAD

**Issue by marcdhansen** [guillermo-navas-palencia/optbinning#175]
I tried modifying the multiclass binning test to use the iris dataset.  When I try to split the "petal length (cm)" column, no split points are returned.  Here is the code I tried:
```
data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names)

variable = "petal length (cm)"
x = df[variable].values
y = data.target

optb = MulticlassOptimalBinning()
optb.fit(x, y)
splits = optb.splits.tolist()
```

Am I doing something wrong?

**Comment by guillermo-navas-palencia** [comment]
Hi @marcdhansen,

You are not doing anything wrong. For the petal columns, it is simply not possible to generate bins with all three target classes. For example "petal length (cm)":
![image](https://user-images.githubusercontent.com/40094942/174884171-a12c8fb9-8944-44e2-9825-633e211eec5f.png)
And now, compare to 'sepal length (cm)':
![image](https://user-images.githubusercontent.com/40094942/174884291-4e747695-8218-483a-b348-f86514b47961.png)

For computing the Jensen-Shannon (multivariate) metric you need pre bins with data samples having all three target categories. In the example above, there is no split point generating two bins with target classes 0, 1 and 2 (for example a split on 4.6 would create two bins, first (-inf, 4.6) with classes 0, 1 and 2, a second one [4.6, +inf) with classes 1 and 2).

**Comment by guillermo-navas-palencia** [comment]
Yes, you could use a Continuous Optimal Binning with a multiclass target, although not recommended:
![image](https://user-images.githubusercontent.com/40094942/174972179-ddde80aa-dd6f-4e71-9b7f-6e8430f17114.png)

**Comment by marcdhansen** [comment]
Thank you!
