### ISSUE TITLE
Binnig multiple independent variables 

### ISSUE THREAD

**Issue by nauanchik** [guillermo-navas-palencia/optbinning#177]
Hi! I am really thankful for your package (beautiful job)! However, I can't use optbinning for multiple independent variables. Is there a way to do it, without writing a loop?

**Comment by guillermo-navas-palencia** [comment]
hI @nauanchik,

Please have a look at the class ``BinningProcess`` http://gnpalencia.org/optbinning/binning_process.html, and the corresponding tutorials: http://gnpalencia.org/optbinning/tutorials.html#binning-process-tutorials.
