### ISSUE TITLE
Problem with pyarrow 

### ISSUE THREAD

**Issue by rafaelhfm** [guillermo-navas-palencia/optbinning#178]
I have installed optbinning 0.14.1 and in the fit of any function I would get the following error:

`[1]    35791 segmentation fault  python test_opt.py`

Not a very verbose error. 

After debugging it I realized the problem was because I had pyarrow 6.0.1 installed. After upgrading it to 8.0.0 it worked. 

Not sure why.

**Comment by guillermo-navas-palencia** [comment]
Hi @rafaelhfm.

I do not know the content of test_opt.py, so difficult to assess whether it was an optbinning-related issue.
