### ISSUE TITLE
Use bins thresholds values to labels the bins

### ISSUE THREAD

**Issue by lcrmorin** [guillermo-navas-palencia/optbinning#180]
Hi, currently there is two options for plots: normal where bins are labeled with bins numbers and 'actual' where the real scale is used. I'd like something in between where the bins are plotted as in the first case but labels used are the bins thresholds values. Would it be possible ?

**Comment by guillermo-navas-palencia** [comment]
I like the idea. Would you be interested in creating a PR?

**Comment by guillermo-navas-palencia** [comment]
Completed.
