### ISSUE TITLE
Monotonic trend with binningprocess 

### ISSUE THREAD

**Issue by boyyonder** [guillermo-navas-palencia/optbinning#183]
When using the scorecard class the binningprocess object is required however I couldn't see anywhere that I could set the monotonic trend within that object.

The monotonic trend can be set within the optimal binning class so I'm not sure if I'm just missing something as I'm still fairly new when it comes to python.

**Comment by guillermo-navas-palencia** [comment]
Hi @boyyonder,

See this example: http://gnpalencia.org/optbinning/tutorials/tutorial_binning_process_FICO_xAI.html#Modeling (cell 8). Please have a look at the parameters ``binning_fit_params`` and ``binning_transform_params`` http://gnpalencia.org/optbinning/binning_process.html#binning-process.
