### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by mmetwalli96** [guillermo-navas-palencia/optbinning#186]
When I am trying to install optbinning in Ubuntu 22.04.1 LT; I get this error message 

![Screen Shot 2022-08-31 at 9 47 46 AM](https://user-images.githubusercontent.com/59425631/187694305-07e7deae-4c5a-469d-a831-ec5bff20833b.png)

How can I solve this issue?

**Comment by guillermo-navas-palencia** [comment]
Hi @mmetwalli96,

It seems that you do not have cmake installed on your Linux. Cmake is needed to install cvxpy (a dependency).

**Comment by mmetwalli96** [comment]
Hello @guillermo-navas-palencia 

Thanks for the prompt response. I installed cmake and it is added to the path, and it is still giving errors. I installed it through pip. Do you have another recommendation or workaround?

**Comment by guillermo-navas-palencia** [comment]
Did you install cmake through pip? this link could help: https://github.com/osqp/osqp-python/issues/4

**Comment by stroyal** [comment]
I've been seeing the same on my M2 chip mac, if you use the below it seems to work.
`pip install osqp==0.4.1`

**Comment by mmetwalli96** [comment]
that really worked

**Comment by guillermo-navas-palencia** [comment]
Thanks @stroyal. I close this issue.
