### ISSUE TITLE
Population stability index after binning

### ISSUE THREAD

**Issue by andreykataev** [guillermo-navas-palencia/optbinning#187]
It would be great to see PSI after optimal binning variable.

**Comment by guillermo-navas-palencia** [comment]
Hi @andreykataev,

The PSI in the context of binary optbinning binning is equivalent to the information value (IV). This information is displayed using ``optb.binning_table.analysis()``. See this example: http://gnpalencia.org/optbinning/tutorials/tutorial_binary.html#Binning-table-statistical-analysis

**Comment by andreykataev** [comment]
@guillermo-navas-palencia not at all, there are general statistics according to the data used in developing. It would be nice to see stability of the binning variable in the dynamics, for example, by months of approval.

+ Often to test the model, it is necessary to implement it through SQL - it would be very cool if the final model could be displayed in the form as SQL script.

**Comment by guillermo-navas-palencia** [comment]
Ok, I understand. This feature is implemented in the context of scorecards: http://gnpalencia.org/optbinning/scorecard.html#monitoring

Tutorial:
http://gnpalencia.org/optbinning/tutorials/tutorial_scorecard_monitoring.html

**Comment by guillermo-navas-palencia** [comment]
BTW, I think the scorecard SQL script is a good idea. Would you like to contribute?

**Comment by guillermo-navas-palencia** [comment]
I close this issue. Please re-open if needed.

**Comment by denmase** [comment]
> BTW, I think the scorecard SQL script is a good idea. Would you like to contribute?

Hi @guillermo-navas-palencia ,

I'm doing quick-and-dirty scorecard SQL in my [fork](https://github.com/denmase/optbinning/blob/master/optbinning/scorecard/scorecard.py#L455-L509). If you are interested, please take a look and if there's anything I can do, please inform me. Pardon the coding style, I just code for practical use now, so most probably the code  is not up to standard yet.

Thanks
