### ISSUE TITLE
Sample Weight not being applied correctly in binning_process when n_jobs != 1

### ISSUE THREAD

**Issue by stroyal** [guillermo-navas-palencia/optbinning#190]
Looks like you made the update to use sample_weight when n_jobs == 1 (as per #124) but not when n_jobs != 1:

**Updates required in [binning_process.py](https://github.com/guillermo-navas-palencia/optbinning/blob/master/optbinning/binning/binning_process.py):**
Lines 1151 & 1163
_From:_
`self.special_codes, self.split_digits)`

_To:_
`self.special_codes, self.split_digits, sample_weight)`

**Comment by guillermo-navas-palencia** [comment]
Thank you @stroyal
