### ISSUE TITLE
WoE transformed values in scorecard

### ISSUE THREAD

**Issue by boyyonder** [guillermo-navas-palencia/optbinning#193]
When building a scorecard using independent variables that have been transformed into WoE values it would be really useful if the scorecard could display the original non transformed values. 

Is this possible?

Happy to provide more info if this isn't clear.

**Comment by guillermo-navas-palencia** [comment]
Hi @boyyonder,

Thanks for proposing this feature. Could you please provide an example to clarify 100%?

**Comment by guillermo-navas-palencia** [comment]
I close this issue. Please reopen if you can provide more details.
