### ISSUE TITLE
Precision on bin widths

### ISSUE THREAD

**Issue by wbolton** [guillermo-navas-palencia/optbinning#195]
Hi, I am running in to issues where the bin width precision makes it appear to be 0 width, is there a way to increase the precision displayed in the binning table? For now I have worked around this by multiplying all values for this variable up by 1000. Apologies if this is documented somewhere I did spend a while looking but may have missed something.
![image](https://user-images.githubusercontent.com/77201847/192565180-78e113c8-e8c1-4ade-a46d-d9117572baa5.png)

**Comment by guillermo-navas-palencia** [comment]
No worries @wbolton. Check: http://gnpalencia.org/optbinning/binning_tables.html#optbinning.binning.binning_statistics.BinningTable.build

**Comment by wbolton** [comment]
Ah amazing, thanks for the quick response!
