### ISSUE TITLE
Question about hyperparams tuning for Scorecard class

### ISSUE THREAD

**Issue by jnsofini** [guillermo-navas-palencia/optbinning#198]
Currently I am trying to do a hyperparameter tuning for the estimator (LogisticRegression in this case) of the Scorecard class. I couldn't figure out an elegant way to do it, so I approached it as follows:

Do a gridsearch on the LogisticRegression and then extract the the best parameters and then reuse those in the LogisticRegression estimator in the Scorecard object. 

This works but I am wondering if there are better ways to achieve this for example

1. Passing an already fitted estimator to the scorecard object
2. Performing hyper params tuning on the estimator directly in the Scorecard object

**Comment by guillermo-navas-palencia** [comment]
Hi @jnsofini.

As a general method, I would choose option 2 treating the Scorecard class as a nested estimator: https://scikit-learn.org/stable/modules/grid_search.html#composite-estimators-and-parameter-spaces.

**Comment by guillermo-navas-palencia** [comment]
I close this issue. Let me know if that worked, and reopen if needed.

**Comment by jnsofini** [comment]
_I have not been able to get it to work by tuning a composite estimator. I have tried the following:_

`from sklearn.model_selection import GridSearchCV
from sklearn.datasets import make_moons
from optbinning import BinningProcess, Scorecard
from sklearn.metrics import roc_auc_score
from sklearn.linear_model import LogisticRegression
import pandas as pd

X, y = make_moons()
X = pd.DataFrame(X, columns=["col1", "col2"])

scorecard = Scorecard(
        binning_process=BinningProcess(variable_names=X.columns.to_list()),
        estimator=LogisticRegression(solver="liblinear", random_state=1)
    )

param_grid = {
    "estimator__penalty": ["l1", "l2"],
    "estimator__C": [1, 2],
    }

scorecard_search = GridSearchCV(
            estimator=scorecard,
            param_grid=param_grid,
            scoring="roc_auc",
            cv = 2,
            n_jobs=-1
        )
print(scorecard_search)
print("Performing gridsearch")

scorecard_search.fit(X, y)
y_pred = scorecard_search.predict_proba(X)[:, 1]
print("The auc is: {auc:3f} ".format(auc=roc_auc_score(y, y_pred)))
print(scorecard_search.best_estimator_)`

-----------------------------------------------------------------------------------
The following is the output. I am showing the part I deem meaningful
-----------------------------------------------------------------------------------

(optbin) C:\Users\search>python -i  gridsearch.py
GridSearchCV(cv=2,
             estimator=ScorecardM(binning_process=BinningProcess(variable_names=['col1',
                                                                                 'col2']),
                                  estimator=LogisticRegression(random_state=1,
                                                               solver='liblinear')),
             n_jobs=-1,
             param_grid={'estimator__C': [1, 2],
                         'estimator__penalty': ['l1', 'l2']},
             scoring='roc_auc')
Performing gridsearch
C:\Users\--\.conda\envs\optbin\lib\site-packages\sklearn\model_selection\_validation.py:770: UserWarning: Scoring failed. The score on this 
train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\--\.conda\envs\optbin\lib\site-packages\sklearn\metrics\_scorer.py", line 355, in _score
    y_pred = method_caller(clf, "decision_function", X)
  File "C:\Users\--\.conda\envs\optbin\lib\site-packages\sklearn\metrics\_scorer.py", line 68, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
AttributeError: 'Scorecard' object has no attribute 'decision_function'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\--\.conda\envs\optbin\lib\site-packages\sklearn\model_selection\_validation.py", line 761, in _score
    scores = scorer(estimator, X_test, y_test)
  File "C:\Users\--\.conda\envs\optbin\lib\site-packages\sklearn\metrics\_scorer.py", line 216, in __call__
    return self._score(
  File "C:\Users\--\.conda\envs\optbin\lib\site-packages\sklearn\metrics\_scorer.py", line 372, in _score
    y_pred = self._select_proba_binary(y_pred, clf.classes_)
AttributeError: 'Scorecard' object has no attribute 'classes_'

**Comment by guillermo-navas-palencia** [comment]
Hi @jnsofini.

If I understand correctly, the Scorecard class would need ``decision_function`` to be suitable for merics_scorer.py. When developing the Scorecard class, I didn't think about it as an estimator but rather as a tailor-made pipeline. Exposing ``decision_function`` should not be easy.

Regarding your code, I can make it run, although it fails silently. I am using Python 3.7 and scikit-learn 1.0.2.
![image](https://user-images.githubusercontent.com/40094942/201177597-5db345cc-56bb-4c51-9d6c-894279c34eee.png)

**Comment by guillermo-navas-palencia** [comment]
I just wrote a quick prototype. I will include it as part of the next release (0.17.x or 0.18.0):

![image](https://user-images.githubusercontent.com/40094942/201182235-c4a224ab-a9c9-43fd-a7ce-f9e0b51bc873.png)

**Comment by jnsofini** [comment]
> Hi @jnsofini.
> 
> If I understand correctly, the Scorecard class would need `decision_function` to be suitable for merics_scorer.py. When developing the Scorecard class, I didn't think about it as an estimator but rather as a tailor-made pipeline. Exposing `decision_function` should be easy.
> 
> Regarding your code, I can make it run, although it fails silently. I am using Python 3.7 and scikit-learn 1.0.2. ![image](https://user-images.githubusercontent.com/40094942/201177597-5db345cc-56bb-4c51-9d6c-894279c34eee.png)

I think in the silence failing, it basically take the first set of param, from the groups i.e (l1, 1)

**Comment by jnsofini** [comment]
Looking forward to the new release!
