### ISSUE TITLE
Default Value for "max_pvalue"

### ISSUE THREAD

**Issue by fra94** [guillermo-navas-palencia/optbinning#199]
https://github.com/guillermo-navas-palencia/optbinning/blob/7806d9d2acd06be6d976ce161b630d27dcd14cde/optbinning/binning/binning.py#L430

I report that in the documentation (http://gnpalencia.org/optbinning/binning_binary.html) it is indicated that the default value for "max_pvalue" is equal to 0.05 but actually is None (which means no test of significance)

**Comment by guillermo-navas-palencia** [comment]
Thanks @fra94.
