### ISSUE TITLE
will it work for unbalanced data : when number of one class is much less for another class?

### ISSUE THREAD

**Issue by Sandy4321** [guillermo-navas-palencia/optbinning#2]
will it work for unbalanced data : when number of one class is much less for another class?
for example
https://github.com/airysen/caimcaim
and
https://cran.r-project.org/web/packages/discretization/discretization.pdf
and
https://en.wikipedia.org/wiki/Discretization_of_continuous_features

not working for unbalanced data

**Comment by guillermo-navas-palencia** [comment]
Hi,

OptBinning is prepared to handle unbalanced data. Do you have a specific dataset in mind? It allows many constraints I recommend you to check the documentation:

http://gnpalencia.org/optbinning/binning_binary.html

Let me know if you need any help!
