### ISSUE TITLE
Setting 'user_splits_fixed' in categorical binning

### ISSUE THREAD

**Issue by nic9lif3** [guillermo-navas-palencia/optbinning#20]
Hi @guillermo-navas-palencia,

There is a problem when I try to setting value to `user_splits_fixed`. Suppose  I have column with raito of event rate in each value like this:  
|   value |     raito |
|-----------:|----------:|
|         -1 | 0.011665  |
|          2 | 0         |
|          3 | 0.0133333 |
|          4 | 0.166667  |
|          7 | 0         |
|          8 | 0.0246041 |
|          9 | 0         |
|         10 | 0.025641  |

Then when I set `user_splits = [[ 2.,  7.,  9.,  3.,  10.,  4.],[8],[-1]]` ,`user_splits_fixed=[True, True, True]`, `monotonic_trend=None`,`dtype='categorical'` 
and the program raises error `ValueError: Fixed user_splits [list([2.0, 7.0, 9.0, 3.0, 10.0, 4.0])] are removed because produce pure prebins. Provide different splits to be fixed.`. What thing is wrong here?

**Comment by guillermo-navas-palencia** [comment]
Hi @nic9lif3,

Thanks, I will try to reproduce your problem.

**Comment by nic9lif3** [comment]
Hi @guillermo-navas-palencia 
The splits result with default option of `OptimalBinning` is `[[ 2., 7., 9., 3., 10., 4. 8],[-1]]`. When I parse this splits as an option into `user_splits` parameter, it return the same error :).

**Comment by guillermo-navas-palencia** [comment]
Hi @nic9lif3,

There was a bug, I just fixed it, thanks for noticing. I acknowledge some tests are missing for the categorical type. I will commit the changes to master with new unit tests in a few minutes.

**Comment by nic9lif3** [comment]
Thanks @guillermo-navas-palencia for your contribute.

**Comment by guillermo-navas-palencia** [comment]
I created this example to reproduce your problem:

    import numpy as np

    np.random.seed(0)
    n = 100000

    x = sum([[i] * n for i in [-1, 2, 3, 4, 7, 8, 9, 10]], [])
    y = list(np.random.binomial(1, 0.011665, n))
    y += list(np.zeros(n))
    y += list(np.random.binomial(1, 0.0133333, n))
    y += list(np.random.binomial(1, 0.166667, n))
    y += list(np.zeros(n))
    y += list(np.random.binomial(1, 0.0246041, n))
    y += list(np.zeros(n))
    y += list(np.random.binomial(1, 0.025641, n))

    user_splits = [[2., 7., 9., 3., 10., 4.], [8], [-1]]
    user_splits_fixed = [True, True, True]

    optb1 = OptimalBinning(dtype="categorical", user_splits=user_splits)
    optb2 = OptimalBinning(dtype="categorical", user_splits=user_splits,
                           user_splits_fixed=user_splits_fixed)

    for optb in (optb1, optb2):
        optb.fit(x, y)
        optb.binning_table.build()
        assert optb.binning_table.iv == approx(0.09345086993827473, rel=1e-6)

After commit a6d015b2e9365ecc05cba48421972c562f7960c7, it must work as expected.

**Comment by nic9lif3** [comment]
Hi, @guillermo-navas-palencia ,

It seems like you change the code of setting user split for categorical. Error unhashable type list raises when I set user split is a list of list.

**Comment by guillermo-navas-palencia** [comment]
Hi @nic9lif3,

No, it has not changed. I just run the previous example with version 0.8.0, and it worked without issues. It would be more helpful if you could attach the error message, my impression is that this error is not OptBinning related.
