### ISSUE TITLE
min_event_rate_diff with monotonic_trend = None

### ISSUE THREAD

**Issue by vavrato** [guillermo-navas-palencia/optbinning#201]
It would be nice to have OptimalBinning min_event_rate_diff functionality with monotonic_trend set to None.
The event_rate_diff functionality is missing in piecewise binning at all, it would be nice to have it there as well.

**Comment by detrin** [comment]
I would like to have this feature as well! Looking at your [code](https://github.com/guillermo-navas-palencia/optbinning/blob/944fef57e1013f1ad8921d1522321791c2d229e5/optbinning/binning/cp.py#L380) it seems like `min_event_rate_diff` is directly added to constrains.

**Comment by guillermo-navas-palencia** [comment]
Hi,

Thanks for the suggestion. I will focus on the OptimalBinning class. To implement such constraints without monotonicity constraints, it is necessary to define how differences are computed. Options:

1. Absolute event rate difference between consecutive bins.
2. Absolute event rate difference between one bin and the rest.

@detrin: The parameter ``min_event_rate_diff`` is only applicable under certain monotonicity constraints. See http://gnpalencia.org/optbinning/binning_binary.html. Indeed, this difference (beta) is easily added to the monotonicity constraint:
![image](https://user-images.githubusercontent.com/40094942/197061104-d6dabc1f-2511-4b3b-90b1-99557ff981b8.png)

Regarding the piecewise binning, are you considering the continuous or discontinuous case?

**Comment by vavrato** [comment]
What I had in mind was choice 1., i.e. merging consecutive bins if their even rate difference smaller than a given bound. Actually, it would make sense to have any two bins to merge in case of categorical features.

Regarding the piecewise binning, I have not given it much thought. Actually, is there a description how do they work? I just saw the graphs in the tutorial and I loved the idea of having non-constant WoE in a bin.

Anyway, thank you for developing this awesome tool and being so responsive!

**Comment by guillermo-navas-palencia** [comment]
PR #207 closes this issue. You can try this new feature using branch develop.
