### ISSUE TITLE
ValueError: not enough values to unpack (expected 8, got 3)

### ISSUE THREAD

**Issue by CarloNicolini** [guillermo-navas-palencia/optbinning#205]
I am using the `ContinuosBinning` with a number of categorical and numerical variables as `X` and a float bounded in `[0,1]` as `y`.
With some of the categorical variables I sometimes get the following error when fitting:

```
File ~/opt/miniconda3/envs/creditfactor/lib/python3.10/site-packages/optbinning/binning/continuous_binning.py:628, in ContinuousOptimalBinning._fit(self, x, y, check_input)
    623         [splits, n_records, sums, ssums, stds, min_t, max_t,
    624          n_zeros] = self._prebinning_refinement(
    625             user_splits, x_clean, y_clean, y_missing, x_special,
    626             y_special, y_others)
    627 else:
--> 628     [splits, n_records, sums, ssums, stds, min_t, max_t,
    629      n_zeros] = self._fit_prebinning(
    630         x_clean, y_clean, y_missing, x_special, y_special, y_others)
    632 self._n_prebins = len(n_records)
    634 self._categories = categories

ValueError: not enough values to unpack (expected 8, got 3)
```

Originally, I was using a `BinningProcess` + `Scorecard` pipeline, but going in the details of the issue I've found it originates in the `ContinuosBinning` class, so I've posted as a problem with it.
By changing the `prebinning_method = "uniform"` in `ContinuosBinning` the issue vanishes, but how do I pass this argument in the `BinningProcess`?

**Comment by guillermo-navas-palencia** [comment]
Hi @CarloNicolini.

I am unable to reproduce this error. I understand you are using Linux and Python 3.10, an environment tested with GitHub actions. You can pass specific parameters using ``binning_fit_params``. For example

```python
binning_fit_params = {v: {'prebinning_method': 'uniform'} for v in variables}
```

http://gnpalencia.org/optbinning/tutorials/tutorial_binning_process_FICO_xAI.html#Modeling

**Comment by guillermo-navas-palencia** [comment]
Hi @CarloNicolini.

The ``ContinuousOptimalBinning`` class had a bug when no prebinning splits were generated. The new release 0.17.0 will fix it. In the meantime, you can use this branch: https://github.com/guillermo-navas-palencia/optbinning/tree/feature/continuous_binning_sample_weight.

To confirm, you should see a similar message when setting ``verbose=True``:
![image](https://user-images.githubusercontent.com/40094942/200092091-a46fb1f4-a1a7-43cf-bbd1-5cec55233930.png)

**Comment by CarloNicolini** [comment]
> Thanks. Could you please send a reproducible example? I am not a macOs user, but I could try that example via GitHub actions.

Many thanks, I've just updated to 0.17.0 and it works without the "uniform" prebinning specification.
