### ISSUE TITLE
RuntimeError: CHECK failed: target + size == res: 

### ISSUE THREAD

**Issue by ssurya1696** [guillermo-navas-palencia/optbinning#208]
Getting a Runtime error 'RuntimeError: CHECK failed: target + size == res:' when I'm trying to fit (optb.fit(x, y))

**Comment by guillermo-navas-palencia** [comment]
Hi @ssurya1696.

I am afraid you need to provide more details (version, solver, and a reproducible example).

**Comment by guillermo-navas-palencia** [comment]
Please re-open if needed.
