### ISSUE TITLE
class_weight does not work in OptimalBinning

### ISSUE THREAD

**Issue by vavrato** [guillermo-navas-palencia/optbinning#222]
The reason is that on this line [here](https://github.com/guillermo-navas-palencia/optbinning/blob/4be85cd2001623cb02fbe43424dfa091859840dc/optbinning/binning/preprocessing.py#L184) you have to call the second and third argument with keywords, i.e.
 `class_weight_ = compute_class_weight(class_weight, classes = classes, y = y)`.

Thanks for the future fix

**Comment by guillermo-navas-palencia** [comment]
Thank you. See: https://github.com/guillermo-navas-palencia/optbinning/commit/bee655978e8b647a42a2728a84e96100863be823
