### ISSUE TITLE
How to modify the result of optimal bin？

### ISSUE THREAD

**Issue by cfkstat** [guillermo-navas-palencia/optbinning#230]
Some missing subcases, or special value subcases less than 5% of the sample proportion, need to be merged into some subcases？

**Comment by guillermo-navas-palencia** [comment]
Hi @cfkstat. To modify the binning results, you can use the parameter ``user_splits`` and ``user_splits_fixed``. See tutorial: http://gnpalencia.org/optbinning/tutorials/tutorial_binary.html#User-defined-split-points
