### ISSUE TITLE
Missing target records all considered as 'Events'

### ISSUE THREAD

**Issue by chapmanh** [guillermo-navas-palencia/optbinning#234]
Hi, thanks again for providing this library. It's helped me immensely!

I wanted to raise something around null values when fitting data. It appears that fitting with records which have a missing target value places the record in the 'Missing' sections, but **automatically considers the records to be events**. This can drastically skew the IVs.

Perhaps it would be clearer and more appropriate if only records with a valid targets contributed to WOE and IV calculations, and if a warning was raised to the user if null target records have been provided?

I've redacted my dataset, but here's a quick example of a metric with about 13% missing target values. For context, I have a dataset with variables for every record, but there are some instances where it is not appropriate to include a particular record.

```
from optbinning import OptimalBinning

def fit_bin(df, variable, target, special_codes, remove_null = True):
    
    if remove_null == True :
        df  = df[[variable, target]][df[target].notnull()]
    
    x = df[variable]
    y = df[target]
    dtype = 'categorical' if str(x.dtypes) == 'object' else 'numerical'
    optb = OptimalBinning(name=variable, dtype=dtype, solver='cp',
                          special_codes=special_codes)

    optb.fit(x,y)
    return optb
```

```
optb = fit_bin(df, v, t, get_special_values(dd, v), remove_null=True)
optb.binning_table.build()
```

yields:
![image](https://user-images.githubusercontent.com/46978481/220347849-5072a702-9f2b-4cc5-966d-4b3e79816fcc.png)

whereas;

```
optb_nulls = fit_bin(df, v, t, get_special_values(dd, v), remove_null=False)`
optb_nulls.binning_table.build()`
```

yields:
![image](https://user-images.githubusercontent.com/46978481/220349988-ce71956a-86d7-4ad8-9a51-18e05231a6df.png)

A huge inflation of the IV due to - what I believe to be - the skew in the distribution of events within each bin.
Thanks,
H

**Comment by guillermo-navas-palencia** [comment]
Hi @chapmanh.

The target cannot contain NaN, however, this is only checked if you set check_input to True when fitting, simply due to performance benefits:
```python
optb = OptimalBinning()
optb.fit(x, y, check_input=True)
```

If you pass NaN in target, which arguably does not make sense, this is the undesired behavior.
