### ISSUE TITLE
Missing and Special bins added to index 0 with  optb.transform

### ISSUE THREAD

**Issue by chapmanh** [guillermo-navas-palencia/optbinning#235]
Me again (apologies!),

As per the title:

example where Special is incorrectly aggregated into bin index 0:
![image](https://user-images.githubusercontent.com/46978481/220413793-6b437435-1025-4f5c-a73d-3dc023039761.png)

and for Missing as well:
![image](https://user-images.githubusercontent.com/46978481/220414069-eb3e9f09-25c7-4276-912a-8bfd414e3b9b.png)

Note the totals of missing/special plus bin 0 match perfectly.

I have not found an instance in my work where I have Missing and Special in the same metric, but would Imagine that in the OptimalBinning class the binning_tables method is doing some pre-processing during or before building which the .transform method is not emulating before looking up the index of the bin and returning the index, so the first 'normal' bin, the Missing bin and the Special bin all return 0 within the transform method.

Thanks,
H

**Comment by guillermo-navas-palencia** [comment]
Hi @chapmanh,

See  https://github.com/guillermo-navas-palencia/optbinning/issues/169. Please read the documentation of the transform method.
