### ISSUE TITLE
Can't enforce the. same bin on different dataset

### ISSUE THREAD

**Issue by rychrr** [guillermo-navas-palencia/optbinning#236]
Hi Dev,

Great job on the optbinning module, it's one I use very frequently.

However, I notice one cannot replicate the binning  on a new data set, for instance if I have trained my data and decide to introduce a new data set for prediction, I am unable to bin the data into the same bin as used for the training.

**Comment by guillermo-navas-palencia** [comment]
Hi @rychrr.

The idea is to use the ``transform`` method to apply the calculated binning to new data. Perhaps you could provide an example to illustrate your issue.

Thanks,
Guillermo
