### ISSUE TITLE
Problem when executing binning_process.fit(X, Y)

### ISSUE THREAD

**Issue by aheneche** [guillermo-navas-palencia/optbinning#237]
Hi! 

I had a code that worked just fine but then a few days later I tried to executed it and it gave me this error:

the code:
dt_train_binned = binning_process.fit(X, Y)

the error:

opt/anaconda3/lib/python3.9/site-packages/ortools/sat/python/cp_model.py:2198: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  self.__solution = cp_model_pb2.CpSolverResponse.FromString(

I'm on a mac M1, could that be the problem? I had previosuly installed the library optbinning without issues

Thank you!

**Comment by guillermo-navas-palencia** [comment]
Hi @aheneche.

I am not sure, there might be some Google OR-Tools related issues with some macOS versions. Which OR-Tools version are you using? did you update to the latest one?
