### ISSUE TITLE
Binning with Equal Counts

### ISSUE THREAD

**Issue by rakshitrao99** [guillermo-navas-palencia/optbinning#238]
Hi!

Is there any way in which I can fix that the number of bins such that in each bin the number of counts remains the same (normally known as equal frequency binning). And this number of bins is user defined. Same as what we normally do in Pandas using cut and qcut functionality.

**Comment by guillermo-navas-palencia** [comment]
Hi  @rakshitrao99.

You should be able to produce such binning using the prebinning_method="quantile" and monotonic_trend=None.

**Comment by rakshitrao99** [comment]
Hi!!
Is there any way we can define the number of bins? 
I am applying the same strategy as you mentioned but still getting only one bin which is from (-inf, inf), instead I want 10 bins. 
Kind of like this: 

<html>
<body>


  | Bin | Count | Count (%) | Non-event | Event | Event rate | WoE | IV | JS
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
(-inf, inf) | 244484 | 0.337092 | 116218 | 128266 | 0.524640 | -0.802711 | 0.236761 | 0.028825
Special | 0 | 0.000000 | 0 | 0 | 0.000000 | 0.0 | 0.000000 | 0.000000
Missing | 480789 | 0.662908 | 369055 | 111734 | 0.232397 | 0.490752 | 0.144748 | 0.017914
  | 725273 | 1.000000 | 485273 | 240000 | 0.330910 |   | 0.381509 | 0.046739


</body>
</html>

Thanks for the help!!!

**Comment by guillermo-navas-palencia** [comment]
Could you provide data or code to reproduce it?

**Comment by guillermo-navas-palencia** [comment]
Re-open if you can provide a reproducible example. Thanks.
