### ISSUE TITLE
Optbinning misses "missings" in binning

### ISSUE THREAD

**Issue by loveis98** [guillermo-navas-palencia/optbinning#250]
Hi! I use optbinning==0.17.3
The problem is incorrect counting of missings while binning process:
![image](https://github.com/guillermo-navas-palencia/optbinning/assets/33670688/377a2d40-fa59-4023-ac3a-b62191ac63c9)
But the real number of missing values is:
![image](https://github.com/guillermo-navas-palencia/optbinning/assets/33670688/05fcbdcf-eb22-449d-a91d-9b0395bb75b6)

Could you fix it?

**Comment by guillermo-navas-palencia** [comment]
Hi @loveis98. Could you please provide data to reproduce the result? I think this is due to the sample_weights you are passing, and the counts are computed using considering the weights, which is correct.
