### ISSUE TITLE
Explain meaning of min_event_rate_diff_x

### ISSUE THREAD

**Issue by nic9lif3** [guillermo-navas-palencia/optbinning#252]
I'm using OptimalBinning2D with parameters min_event_rate_diff_x, min_event_rate_diff_y. The result of the event rate between bins doesn't make sense with this config. Can you explain the reasonable of the result?
![image](https://github.com/guillermo-navas-palencia/optbinning/assets/17736568/94d472b7-9862-4781-bd24-f0d0a9bea4ff)
![image](https://github.com/guillermo-navas-palencia/optbinning/assets/17736568/fa563e66-220d-4d76-bb78-e9e7f4521b9f)

**Comment by guillermo-navas-palencia** [comment]
Hi. Indeed, it does not look right. Could you please provide the data to reproduce it?

**Comment by guillermo-navas-palencia** [comment]
Closed since no data was provided.
