### ISSUE TITLE
Manual Binning : Everything binned in a single bin. Status: INFEASIBLE

### ISSUE THREAD

**Issue by priyankamishra31** [guillermo-navas-palencia/optbinning#257]
Hi,

I've been trying to use the optbinning library for feature binning, specifically employing manual binning with user-defined split values. However after running the binning process, I encountered an issue, resulting in all feature values being binned into a single bin (from -inf to inf)

- Upon inspection of the logs, I came across the following message: "Optimal Binning Terminated. Status: INFEASIBLE." 
- Additionally, all general metrics derived from binning_table.analysis were reported as 0.00, and the monotonic trend was marked as 'undefined'.

Could you help with this issue.

**Comment by guillermo-navas-palencia** [comment]
Hi @priyankamishra31,

The status INFEASIBLE means that the provided user splits make the problem infeasible (i.e., the mathematical formulation is not correct). If using user-splits, I suggest you use ``monotonic_trend=None`` to disallow the auto monotonic algorithm.

**Comment by priyankamishra31** [comment]
Thanks for the quick response :-) . Setting the 'monotonic_trend=None' worked for me.
