### ISSUE TITLE
Manual Binning Error : Pure prebins error 

### ISSUE THREAD

**Issue by priyankamishra31** [guillermo-navas-palencia/optbinning#258]
I've been trying to manually bin a feature using 'user_splits' , but after running the binning process I'm getting the error

`ValueError: Fixed user_splits [['London'],['NewYork'],['Sydney']] are removed because produce pure preens. Provide different splits to be fixed. `

Could you please help with this ?

**Comment by guillermo-navas-palencia** [comment]
Hi @priyankamishra31.

The message means that for these categories the target is either all 0 or all 1 (I defined these cases as pure prebins).

**Comment by priyankamishra31** [comment]
Thanks for the quick response :-). Is there a way we could get the feature binning even in the case of pure bins ?

**Comment by guillermo-navas-palencia** [comment]
Unfortunately, the calculation of the Information Value (IV) and other metrics require event rates strictly greater than 0 and below 1.
