### ISSUE TITLE
BinningProcess special_codes

### ISSUE THREAD

**Issue by siempreasha** [guillermo-navas-palencia/optbinning#259]
Maybe in BinningProcess  special_codes is same for all variables for input data. But var A has special_codes like 'special_a': [0], 'special_b': [999999999], and var B has special_codes [-99, -999]. So Optbinning can handle those situation if we run the code each other. However, we want to use total data to calculate the result of binning.

**Comment by guillermo-navas-palencia** [comment]
Hi @siempreasha. Indeed, ``special codes`` during instantiation of a BinningProcess applies these codes to all variables. To pass specific special values use the parameter ``binning_fit_params``. See example here: http://gnpalencia.org/optbinning/tutorials/tutorial_binning_process_FICO_xAI.html#Modeling
