### ISSUE TITLE
Plot: handling of add_special and add_missing when show_bin_label is True

### ISSUE THREAD

**Issue by ericlecoutre** [guillermo-navas-palencia/optbinning#262]
Hi

I observe a different behavior between

`binning_table.plot(add_missing=False, add_special=False, show_bin_labels=False)`
 
that removes correctlyt the two 
options related to Special and Missing
and 

`binning_table.plot(add_missing=False, add_special=False, show_bin_labels=True)`

That will strill display the two slots for Missing and Special.

I would find it more adequate to remove those ones.

**Comment by guillermo-navas-palencia** [comment]
I agree, that was not the intended behavior.
