### ISSUE TITLE
Wrong reference feature in special_codes_y in preprocessing_2d.split_data_2d

### ISSUE THREAD

**Issue by phruekc** [guillermo-navas-palencia/optbinning#263]
https://github.com/guillermo-navas-palencia/optbinning/blob/73aee82008ebe88b732430e7c5764da57fb4d3ae/optbinning/binning/multidimensional/preprocessing_2d.py#L86C26-L86C26

Script preprocessing_2d, line 86. I think it supposed to be
'''special_mask_y = pd.Series(y).isin(special_codes_y).values'''

Thanks.

**Comment by guillermo-navas-palencia** [comment]
Yes, thanks for letting me know.
