### ISSUE TITLE
Memory error/kernel restarting

### ISSUE THREAD

**Issue by nitinjethwani7** [guillermo-navas-palencia/optbinning#265]
Hi ,I am trying to use scorecard method.When i am trying to fit on x_train,y_train .It runs for 10 mins and give me memory error.I have 600gb memory on python and my X_train,y_train shape is 600000,12.Please guide oj urgent basis.

binning_process = BinningProcess( variable_names=variable_named)
# 3) Fit and transform dataset

df_train_binned = binning_process.fit_from_dict(dict_optb)

# 1) Define a linear estimator (model)
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
# 2) Instatiate a ScoreCard and fit to dataset
scaling_method = "min_max"
scaling_method_data = {"min": 200, "max": 400}

scorecard = Scorecard(
    target='TARGET',
    binning_process=binning_process,
    estimator=logreg,
    scaling_method=scaling_method,
    scaling_method_params=scaling_method_data,
    intercept_based=False,
    reverse_scorecard=True,
)
scorecard.fit(X_train,y_train)

scorecard_summary = scorecard.table(style="detailed").round(3)

# Get the scorecard table from the scorecard object
scorecard_table = scorecard.table(style="detailed")

# Print the scorecard table
print(scorecard_table)

y_pred = scorecard.predict_proba(X)[:, 1]

score = scorecard.score(X)

import pickle

# To pickle a Scorecard object
with open('scorecard_model.pickle', 'wb') as pfile:
   pickle.dump(scorecard, pfile)
    
# To unpickle it
with open("scorecard_model.pickle", 'rb') as scorecard_pickle:
    scorecard_production = pickle.load(scorecard_pickle)
    
# To use the Scorecard model for predictions in production
# For one sample
scorecard_production.score(df_application_test.iloc[0:1, :])

# For a few samples
scorecard_production.score(df_application_test.iloc[0:3, :])

**Comment by guillermo-navas-palencia** [comment]
Hi @nitinjethwani7.

This is unexpected. I have used the Scorecard class with bigger datasets and a lot less memory. Could you try to fit the binning processing within the Scorecard (avoiding ``fit_from_dict``)?

**Comment by nitinjethwani7** [comment]
> Hi @nitinjethwani7.
> 
> This is unexpected. I have used the Scorecard class with bigger datasets and a lot less memory. Could you try to fit the binning processing within the Scorecard (avoiding `fit_from_dict`)?

Hi Sir it got resolved. But now I have a logical problem.I went through the SAS document which gives you subscores/points but how do you use min max scaling in that?I had final scores which had a range,and kept it between minimum and maximum but how does it explains logically?

**Comment by nitinjethwani7** [comment]
I am really confused on how did you did scaling with min_max parameters. The Scorepoints points will return you unscaled values But how do you scale it to desired points. For example Below are the inputs of one of the bins and their corresponding point is 37.558 points.Can you tell me how did you arrived at this with the following information. My min score is 180 and max score is 490. I understood that you calculated. Points=WoE⋅Coefficient=0.246⋅(−0.835)=−0.20541

However, this is the unscaled points value. The method to scale this to the range of 180 to 490 is not detailed in the link.Please help me on how did you arrived on the scaled value: 37.558 .

My scorecard code is scorecard=optbinning.Scorecard(binning_process=binning_process,estimator=estimator,scaling_method="min_max",scaling_params=scaling_method_params={"min": 190, "max": 490})

Also when i check model.coef_ for each of my variable the coef is are different to what i get in scorecard.table(style="detailed"). Why so?Looking forward for your reply.



# Given values
woe = 0.246
coefficient = -0.835
intercept = -3.49497604
min_score = 180
max_score = 490

**Comment by guillermo-navas-palencia** [comment]
Please have a look at this: https://es.mathworks.com/help/finance/creditscorecard.formatpoints.html and follow the implementation.
