### ISSUE TITLE
How to create interaction variables like we do in SAS ?

### ISSUE THREAD

**Issue by nitinjethwani7** [guillermo-navas-palencia/optbinning#268]
Below is the link of creating interaction variables. Can you help me how we can do in optbinning?

https://documentation.sas.com/doc/en/emref/14.3/n0f3ix7imzm4xrn1773i0xuq47mj.htm#p0jezipvd82gs9n1slz6asqcea7b

**Comment by guillermo-navas-palencia** [comment]
As I see it, you can either multiply the two variables and apply optbinning or use the binning 2d method.
