### ISSUE TITLE
Shapely values on Scorecard object

### ISSUE THREAD

**Issue by hermanashley** [guillermo-navas-palencia/optbinning#274]
Hi there!

Our team is interested in checking out the Shapely values associated with our Scorecard model developed using optbinning. I'm wondering if there is an out-of-the-box way to do this, or if this functionality could be added eventually. 

Sr far, I've tried the [SHAP ](https://shap.readthedocs.io/en/latest/index.html) module. However this is designed to work with sklearn, so when I tried to load our model into an explainer from their library it doesn't recognize what type of model I am giving it. Error is 

`An unknown model type was passed: <class 'optbinning.scorecard.scorecard.Scorecard'>`

Any help is appreciated. Thanks!

**Comment by guillermo-navas-palencia** [comment]
Hi. A workaround is using the fitted logistic regression and the transformed WOE matrix. Some OptBinning users are already doing it.

**Comment by nitinjethwani7** [comment]
> Hi. A workaround is using the fitted logistic regression and the transformed WOE matrix. Some OptBinning users are already doing it.

Can you guide us to any relatable notebook or reproduce results for our convenience?

**Comment by guillermo-navas-palencia** [comment]
> > Hi. A workaround is using the fitted logistic regression and the transformed WOE matrix. Some OptBinning users are already doing it.
> 
> Can you guide us to any relatable notebook or reproduce results for our convenience?

Sorry, I don't have time for that.

**Comment by guillermo-navas-palencia** [comment]
This paper might be relevant: https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4637305
