### ISSUE TITLE
python setup.py install not completing

### ISSUE THREAD

**Issue by alexliap** [guillermo-navas-palencia/optbinning#276]
hello, i would like to contribute to this project but when i cloned the project in my Mac(M1) and run the command python setup.py install the process stopped at some stages.
The most common error was "error: The 'X>=some_version' distribution was not found and is required by cvxpy".
To fix it i was always running conda install X adn then rerun the python setup.py install command.

Could this be fixed just by adding those packages to requirements.txt or in some other way?

**Comment by guillermo-navas-palencia** [comment]
I think I need more details. Could you please be more specific. I am not a Mac user, but this problem was not reported on Linux or Windows.

**Comment by alexliap** [comment]
its ok now i learned that python 'setup.py install' shouldnt be used
instead 'pip install -e .' is the right way to 'install' the project in editable mode in order to contribute
