### ISSUE TITLE
MulticlassBinningTable WoE

### ISSUE THREAD

**Issue by alexliap** [guillermo-navas-palencia/optbinning#280]
Does it make sense to provide WoE values for splits in the multiclass case? I know it is a measure of separation of one class from another but in the multiclass case could it be interpreted as a measure of separation of one class from the others. 

If its ok to say this then I think it would useful to implement it on the MulticlassBinningTable class, as I see it only provides event rates at this moment.

**Comment by guillermo-navas-palencia** [comment]
In my experience, WoE for multiclass binning are not as intuitive and useful. However, there is the option to transform using WoE. Read the docs: https://gnpalencia.org/optbinning/binning_multiclass.html#optbinning.MulticlassOptimalBinning.fit_transform.
