### ISSUE TITLE
Get IV of each feature after applying MulticlassOptimalBinning in multiclass dataset (>2 labels)

### ISSUE THREAD

**Issue by juyjuyy** [guillermo-navas-palencia/optbinning#290]
The dataset I used had `three labels`, and I applied `MulticlassOptimalBinning for binning processing` and then `built binning_table`. The binning_table has many values in the analysis report. Still, I could `not understand the quality_score` value which the formula in the paper "Optimal binning: mathematical programming formulation" has constraints with `IV variable`. Still, the MulticlassOptimalBinning class `doesn't have any property or methods to help access IV` in the multiclass classification problem.

> Here is the picture for my code:

![Screenshot 2023-12-10 161739](https://github.com/guillermo-navas-palencia/optbinning/assets/106720323/9655b8e3-4ff5-4ca0-a5c7-0130d4d246d8)

> And the picture for a formula in the paper:

![Screenshot 2023-12-10 153721](https://github.com/guillermo-navas-palencia/optbinning/assets/106720323/bd68b3af-7b30-4c1d-8c95-64482045d4e2)

![Screenshot 2023-12-10 153732](https://github.com/guillermo-navas-palencia/optbinning/assets/106720323/d767852a-491f-41b8-8c77-b3e5e17dbb43)

**Comment by guillermo-navas-palencia** [comment]
Hi @juyjuyy. 

Note that binning quality score for multiclass target is slightly different: https://github.com/guillermo-navas-palencia/optbinning/blob/master/optbinning/binning/metrics.py#L347. It replaces the IV with the normalized Jensen-Shannon divergence. The ``js`` property can be retrieved from the multiclass binning table: https://github.com/guillermo-navas-palencia/optbinning/blob/master/optbinning/binning/metrics.py#L347.

**Comment by juyjuyy** [comment]
Thank you for your response @guillermo-navas-palencia. After executing the analysis, I have known the properties of binning_table, but I don't get it now. I'm not too good at math, so I don't know the difference between the normalized Jensen-Shannon divergence applied to `js` and the Jeffrey divergence applied to `iv`. 
- Can you explain it or suggest some tutorial documentation explaining this difference? 
- And, the main problem here is that I need `iv` to choose important fields in the dataset, but I cannot calculate, then rank them for my experiment. It raises the question "Can `js` replace `iv` in my problem? How can I prove it?"

**Comment by juyjuyy** [comment]
Can you suggest some documents related to the problem I have?

**Comment by guillermo-navas-palencia** [comment]
I use the Jensen Shannon for binary and multiclass. See https://en.wikipedia.org/wiki/Jensen%E2%80%93Shannon_divergence. 
![image](https://github.com/guillermo-navas-palencia/optbinning/assets/40094942/62aa33b4-5d7c-49d8-bc0e-5c5afa4b422f)

Yes, you can rank by JS. Both are divergence measures.

**Comment by juyjuyy** [comment]
Thank you for your response @guillermo-navas-palencia , 
I wonder why both `IV `and `JS` value exists in the binning table with binary classification, but the multi-class classification exists only `JS.` Could you explain the theory for that? Is `IV` not used for multi-class problem?
Please help me, I really need your reply.

**Comment by guillermo-navas-palencia** [comment]
1. The IV is a divergence measure only suitable for binary target. The JS divergence generalizes the IV allowing multiple categories (multi-class problem).
2. The IV, unlike JS, is unbounded. I found, experimentally, that IV is commonly 5-10 times larger than JS for a binary target. Therefore, a value above 0.02 might work, although I suppose that depends on the number of classes. This is a problem I haven't investigated.
