### ISSUE TITLE
WoE monotonicity prediction with ML

### ISSUE THREAD

**Issue by alexliap** [guillermo-navas-palencia/optbinning#292]
Could you please explain how you predict the woe monotonicity  for a variable? 
I tried to read the relevant paper but didn't quite understand it.
Up to now in my company we have been figuring it out by binning the variable manually.
It would be very useful to understand how its done automatically and not just take it as a black box.

**Comment by guillermo-navas-palencia** [comment]
Hi @alexliap.

I developed an ML algorithm (a simple decision tree) capable of predicting the monotonicity maximizing the Information Value. The [features](https://github.com/guillermo-navas-palencia/optbinning/blob/master/optbinning/binning/auto_monotonic.py) of the model are designed to characterize a prebinning solution. The decision tree is simple, so to make it fast, it is implemented as a set of [rules](https://github.com/guillermo-navas-palencia/optbinning/blob/master/optbinning/binning/auto_monotonic.py#L231). The paper explains in detail the training process and the resulting prediction metrics.
