### ISSUE TITLE
Count % on WOE plot

### ISSUE THREAD

**Issue by SandipKhaire** [guillermo-navas-palencia/optbinning#294]
How can we get count % on top of each bin ?
![image](https://github.com/guillermo-navas-palencia/optbinning/assets/16544802/0e414624-6ff7-4bc2-a7c5-dd1f6ee7f8a6)

**Comment by guillermo-navas-palencia** [comment]
Hi @SandipKhaire.

This level of customization is not possible with the current API.

**Comment by guillermo-navas-palencia** [comment]
I close the issue. Feel free to develop a new feature with this parameter.
