### ISSUE TITLE
plot savefig issue

### ISSUE THREAD

**Issue by SandipKhaire** [guillermo-navas-palencia/optbinning#295]
When i savefig plot then it is not getting full plot. i.e it getting cropped as you can see below **optb.binning_table.plot(metric="woe",show_bin_labels=True,savefig='dt1_.png')**  
![image](https://github.com/guillermo-navas-palencia/optbinning/assets/16544802/3fa41a83-2f82-4f94-87ef-f136cde1584d)

**Comment by guillermo-navas-palencia** [comment]
Hi @SandipKhaire.

The next release will solve this issue. See: https://github.com/guillermo-navas-palencia/optbinning/pull/279
