### ISSUE TITLE
Possible to upgrade the dependency? 

### ISSUE THREAD

**Issue by skwskwskwskw** [guillermo-navas-palencia/optbinning#302]
![image](https://github.com/guillermo-navas-palencia/optbinning/assets/7208012/3c0b545f-3ff6-4237-91a9-ab0bacab1e8b)

Hi, here's the warning when I try to run it in current Kaggle kernel. Possible to have the dependency upgraded?

**Comment by guillermo-navas-palencia** [comment]
Hi @skwskwskwskw.

The requirements are clear not upper constrained: https://github.com/guillermo-navas-palencia/optbinning/blob/master/requirements.txt#L3. I think ortools version 9.4.1874 is the last version supporting Python 3.6 (not sure what Python version you are using). However, you can always upgrade ortools separately.
