### ISSUE TITLE
Axis labels are cut off when saving the table plot to a file

### ISSUE THREAD

**Issue by josp70** [guillermo-navas-palencia/optbinning#303]
We are generating chart in files but the axis labels are cut off in the generated files.

If we pass `bbox_inches='tight'` in the call to `plt.savefig` then the rendered labels are not cut off. 

As a more general fix we can modify the method `BinningTable.plot` and redefined method in derived classes to accept a dictionary argument `save_kwargs` to be expanded in the call to  `plt.savefig`

**Comment by josp70** [comment]
A pull request has been proposed for this feature: #304

**Comment by guillermo-navas-palencia** [comment]
Thanks, I closed this issue since there is a PR fixing it.
