### ISSUE TITLE
Passing manual bins into BinningProcess

### ISSUE THREAD

**Issue by rupakbanerjee77** [guillermo-navas-palencia/optbinning#309]
Hello sir,

The optbinning library has been wonderful and I am using it to build scorecards in my bank. However, one challenge I am facing related to pass the manually created bins/splits into the BinningProcess. Is it possible to pass a certain bins which are not optimal but are required from the business point of view and needs to be included in the scorecard.

Please show with an example.

Regards,
Rupak Banerjee

**Comment by guillermo-navas-palencia** [comment]
Hi @rupakbanerjee77.

The BinningProcess has the parameter ``binning_fit_params``. In this [tutorial](https://gnpalencia.org/optbinning/tutorials/tutorial_binning_process_FICO_xAI.html), Cell 8, there is an example. In your case, you just need to pass a dictionary with keys ``user_splits`` and ``user_splits_fixed`` for each variable requiring manual splits.

**Comment by rupakbanerjee77** [comment]
Thank you sir for your support, it worked.

Regards,
Rupak Banerjee
