### ISSUE TITLE
Result of default OptimalBinning is worse compare with the one that has more restrictions 

### ISSUE THREAD

**Issue by nic9lif3** [guillermo-navas-palencia/optbinning#311]
Hi @guillermo-navas-palencia,

Today I found a weird result with OptimalBinning,

If I use this code, the result will give the IV total is 0.001707
```python
bin=optbinning.OptimalBinning(
    min_prebin_size=0.01,
    max_n_prebins=40,
#     monotonic_trend='ascending'
)
bin.fit(data_train['avginstallast24m_3658937A'],data_train['target'])
bin.binning_table.build()
```
![image](https://github.com/guillermo-navas-palencia/optbinning/assets/17736568/ff19fc66-6693-46b6-9617-ffb50bf839a6)
But when I add the monotonic_trend constraint, it will give a better IV 0.005960
```python
bin=optbinning.OptimalBinning(
    min_prebin_size=0.01,
    max_n_prebins=40,
    monotonic_trend='descending'
)
bin.fit(data_train['avginstallast24m_3658937A'],data_train['target'])
bin.binning_table.build()
````
![image](https://github.com/guillermo-navas-palencia/optbinning/assets/17736568/fb4b8cd4-c389-49e9-a60e-bbe50fef1387)
This data can be found here
[datatest.csv](https://github.com/guillermo-navas-palencia/optbinning/files/14860504/datatest.csv)
Could you explain why it happened? Perhaps the fewer contains, the higher the IV?
Thanks.

**Comment by guillermo-navas-palencia** [comment]
Hi @nic9lif3,

The ``monotonic_trend="auto"`` is not infallible. In this particular case, the predicted monotonic trend was not optimal. In general, when event rates are close to flat, the algorithm might fail. However, this situation is much more unlikely for features with medium/high IV.
