### ISSUE TITLE
Can optbinning  really work with multi-class classification? and build scorecard model using Scorecard() function?

### ISSUE THREAD

**Issue by juyjuyy** [guillermo-navas-palencia/optbinning#312]
![image](https://github.com/guillermo-navas-palencia/optbinning/assets/106720323/bd381e89-38f2-440d-b113-6c87f4fb596e)
I used `BinningProcess` function for the multiclass binning process, the Logistic Regression model from `sklearn` to be an estimator, and `scorecard` function to show the point corresponding to each value of variables. So I have two questions here:
1. What are the differences between `BinningProcess` and `MulticlassOptimalBinning` while both of them can be used to solve multiclass problems?
2. Can `Optbinning` execute making points in the scorecard process? If have, can you show me how to use that? If not, please can you suggest other solutions with multiclass classification, because then I want to convert the coefficient of the model into points in the scorecard?

**Comment by guillermo-navas-palencia** [comment]
Hi @juyjuyy

1. ``BinningProcess`` calls internally ``MulticlassOptimalBinning`` if a multiclass target is provided.
2. The ``Scorecard`` class does not support a multiclass target. I honestly don't know how to convert weighted WoE to proper scores.

Only binary and continuous targets are supported.
http://gnpalencia.org/optbinning/scorecard.html
