### ISSUE TITLE
The feature of numpy parallel can improve the efficiency of variable transform

### ISSUE THREAD

**Issue by cfkstat** [guillermo-navas-palencia/optbinning#318]
When I transform large amounts of data, such as more than 2 million, the transform efficiency is relatively low, and the python package dpnp supports parallelism。

**Comment by guillermo-navas-palencia** [comment]
Hi @cfkstat.

Thanks for proposing this enhancement. I understand that ``transform`` for large datasets might be slow, but dpnp is an additional dependency which might only benefit Intel processors. Therefore, I discard its usage.
