### ISSUE TITLE
RuntimeWarning: invalid value encountered in log

### ISSUE THREAD

**Issue by karpenk** [guillermo-navas-palencia/optbinning#330]
# RuntimeWarning: invalid value encountered in log 
### Handling Edge Cases in `transform_event_rate_to_woe` [function](https://github.com/guillermo-navas-palencia/optbinning/blob/aebe16b4d5f32662d355cac1cbf01056f2246eb2/optbinning/binning/transformations.py#L19)

The `transform_event_rate_to_woe` function can sometimes encounter edge cases that result in `RuntimeWarning` due to invalid values. These edge cases typically occur when the `event_rate` is 0, 1, or falls outside the valid range (0, 1). To prevent these warnings and ensure the function behaves as expected, we can modify the function to handle these scenarios explicitly.

return np.log((1. / event_rate - 1) * n_event / n_nonevent)

### Problematic Edge Cases

- **Event Rate of 0:** A zero event rate could lead to a log(0) operation, which is undefined and results in a warning or an error.
- **Event Rate of 1:** Similarly, an event rate of 1 could lead to a log(∞) operation, which is also problematic.
- **Event Rate Outside the Valid Range (0, 1):** Any event rate outside the range (0, 1) is invalid and should be caught and handled.

### Modified Function

Below is the modified `transform_event_rate_to_woe` function that handles these edge cases:

```python
import numpy as np


def transform_event_rate_to_woe(event_rate, n_nonevent, n_event):
    """Transform event rate to WoE.

    Parameters
    ----------
    event_rate : array-like or float
        Event rate.

    n_nonevent : int
        Total number of non-events.

    n_event : int
        Total number of events.

    Returns
    -------
    woe : numpy.ndarray or float
        Weight of evidence.
    """
    # clip event_rate to avoid exactly 0 or 1 values
    event_rate = np.clip(event_rate, 1e-15, 1 - 1e-15)

    # replace zero n_event or n_nonevent with a small positive value
    n_event = max(n_event, 1e-15)
    n_nonevent = max(n_nonevent, 1e-15)

    return np.log((1.0 / event_rate - 1) * n_event / n_nonevent)

**Comment by lcrmorin** [comment]
Wouldn't it be better to be handled as numpy +/- inf ?
Or at least the epsilon (1e-15) be a parameter of the transformation function ?

**Comment by guillermo-navas-palencia** [comment]
Hi @karpenk. The reality is that the function works as expected, the KL divergence is not defined when probabilities are outside the range (0, 1). OptBinning classes supporting a binary target implement a refinement routine to pre-merge the so-called pure bins (i.e., bins with target all 0 or 1).
