### ISSUE TITLE
General packaging improvements/upgrades

### ISSUE THREAD

**Issue by jmahlik** [guillermo-navas-palencia/optbinning#337]
Hello,

I noticed a few deprecations and potential packaging issues when I was running the tests.

Mostly deprecations and upgrading to allow numpy 2.0+.

I divided them out into two separate PR's to make things easier to review.

* https://github.com/guillermo-navas-palencia/optbinning/pull/335
* https://github.com/guillermo-navas-palencia/optbinning/pull/336

I had a few test failures when running locally on master. It's possible the failures are because I'm on windows. The same tests fail both before and after each of the changes, so it seems the behavior remains unchanged.

Local failures are in the details if that helps. Possibly a floating point precision thing.

<details>

```console
FAILED tests/test_binning_piecewise.py::test_default - assert 5.874746027487957 == 5.87152846 ± 5.9e-06
FAILED tests/test_binning_piecewise.py::test_default_discontinuous - assert 5.844658251811547 == 5.84252707 ± 5.8e-06
FAILED tests/test_binning_piecewise.py::test_bounds_transform - assert array([ 3.991... -3.25653732]) == approx([3.989...38 ± 3.3e-06])
FAILED tests/test_binning_piecewise.py::test_bounds_fit_transform - assert array([ 3.991... -3.25653732]) == approx([3.989...38 ± 3.3e-06])
FAILED tests/test_binning_piecewise.py::test_solvers - assert 5.874746027487957 == 5.87152846 ± 5.9e-06
FAILED tests/test_scorecard.py::test_default - assert -43.5354465187911 == -43.65762593147646 ± 4.4e-05
FAILED tests/test_scorecard.py::test_scaling_method_pdo_odd - assert -608.2909715472422 == -612.2266586867094 ± 6.1e-04
FAILED tests/test_scorecard.py::test_rounding - assert 200.0 == 201 ± 2.0e-04
FAILED tests/test_scorecard.py::test_rounding_pdo_odds - assert -609.0 == -612 ± 6.1e-04
FAILED tests/test_scorecard.py::test_predict_score - AssertionError: assert array([1.1881...99982719e-06]) == approx([1.152...06 ± 9.8e-12])
FAILED tests/test_scorecard_monitoring.py::test_default_binary - assert 0.002224950381423254 == 0.003536079105130241 ± 3.5e-09
================================================= 11 failed, 162 passed, 72 warnings in 252.16s (0:04:12) ==================================================
```

<details>

Let me know thoughts or if you desire any changes. Happy to adjust.

**Comment by guillermo-navas-palencia** [comment]
Thanks a lot for looking into this. I already approved both PRs. There are a few test failures due to changes in CVXPY default solvers (optbinning piecewise). They need to be updated.

**Comment by jmahlik** [comment]
I will rebase #336 and resolve the failing tests.

**Comment by jmahlik** [comment]
I updated the tests with what the current versions of the packages produce.

* The results in `tests/test_scorecard.py` are a bit different. I'm not sure if we're trying to maintain the exact current behavior or if this difference is acceptable. Might need a look over.
* Should the png and csv files in `tests/results` be commited back to the repo? I assume so but they get overwritten when the tests run. I can push them up but it was a pretty big diff.

**Comment by guillermo-navas-palencia** [comment]
Version 0.20.0 released. Thanks!
