### ISSUE TITLE
How to get split points of fitted ContinuousOptimalBinning class on categorical variable

### ISSUE THREAD

**Issue by Kovo121** [guillermo-navas-palencia/optbinning#341]
I'm trying to use optimal binning on a continuous target variable and a categorical feature. I've noticed that the "splits" property returns the binned input categories, but it doesn't provide the target mean split points used to create these bins. Is there a way to retrieve these split points?

**Comment by guillermo-navas-palencia** [comment]
Hi @Kovo121.

Yes, this is hidden, but you can retrieve them via "self._splits_optimal".

**Comment by guillermo-navas-palencia** [comment]
Could you please confirm and close the issue? Thanks @Kovo121

**Comment by Kovo121** [comment]
Hi @guillermo-navas-palencia .
After looking into it more, I found out that self._splits_optimal isn’t actually the target mean split points. Instead, it’s a listof indices pointing to a list of categories sorted by their target variable means. With that figured out, I was able to identify the actual target mean split points.
