### ISSUE TITLE
Quick questions

### ISSUE THREAD

**Issue by similang** [guillermo-navas-palencia/optbinning#40]
Nice package I came across. By the way, may I know:
1. how to remove special/missing rows from binning_table when doing the plotting? 
2. how to do customised binning.

Thanks.

**Comment by guillermo-navas-palencia** [comment]
Hi,

1. Currently, there is no option to remove these rows, but it could be added in the next release. I would add parameters ``add_missing`` and ``add_special`` in binning_table.plot() function, both with default value True.
2. You can use parameters ``user_splits`` and ``user_splits_fixed``. See example http://gnpalencia.org/optbinning/tutorials/tutorial_binary.html#User-defined-split-points.

Let me know if you have more questions.

Best,
Guillermo

**Comment by skw1990** [comment]
Hi, I am not sure if it has been implemented  by perhaps can create rules for the binning (i.e: upper limit column)

**Comment by guillermo-navas-palencia** [comment]
Hi, could you provide an example to clarify?

**Comment by skw1990** [comment]
Hi, for example on page: http://gnpalencia.org/optbinning/tutorials/tutorial_scorecard_binary_target.html; 

say I have another new dataset, how should I score it with the points?

**Comment by skw1990** [comment]
> Hi,
> 
> 1. Currently, there is no option to remove these rows, but it could be added in the next release. I would add parameters `add_missing` and `add_special` in binning_table.plot() function, both with default value True.
> 2. You can use parameters `user_splits` and `user_splits_fixed`. See example http://gnpalencia.org/optbinning/tutorials/tutorial_binary.html#User-defined-split-points.
> 
> Let me know if you have more questions.
> 
> Best,
> Guillermo

Also on the above, if I want to run the 'binningprocess', how to just selective split for one variable? Seems like the example is only applicable to single variable. 

Many thanks for the prompt response.

**Comment by guillermo-navas-palencia** [comment]
> Hi, for example on page: http://gnpalencia.org/optbinning/tutorials/tutorial_scorecard_binary_target.html;
> 
> say I have another new dataset, how should I score it with the points?

you can score it with the method ``score``, but you need to make sure that the new dataset contains the same columns that the one used for training.

**Comment by guillermo-navas-palencia** [comment]
> > Hi,
> > 
> > 1. Currently, there is no option to remove these rows, but it could be added in the next release. I would add parameters `add_missing` and `add_special` in binning_table.plot() function, both with default value True.
> > 2. You can use parameters `user_splits` and `user_splits_fixed`. See example http://gnpalencia.org/optbinning/tutorials/tutorial_binary.html#User-defined-split-points.
> > 
> > Let me know if you have more questions.
> > Best,
> > Guillermo
> 
> Also on the above, if I want to run the 'binningprocess', how to just selective split for one variable? Seems like the example is only applicable to single variable.
> 
> Many thanks for the prompt response.

The BinningProcess includes the parameter ``binning_fit_params``. Example:

```python
binning_fit_params = {
    "my_variable": {"user_splits": [1.2, 1.8, 2.3], "user_splits_fixed" = [False, True, True]}
}
```
See example: http://gnpalencia.org/optbinning/tutorials/tutorial_binning_process_FICO_xAI.html

**Comment by skw1990** [comment]
Thanks but I think the above is not working (so far it only works with float without missing).  I would attach the data here with the code I used here together with the errors.

(a) For variable (dtype = float) with missing 
`params = {"I1": {"user_splits": [ 1.,2.,3.,4.,5.,np.nan], "user_splits_fixed" : [True, True, True, True,True, True ]}}
optb = BinningProcess(['O1','O2','F1','I1'], categorical_variables=['O1','O2'], binning_fit_params  = params)

optb.fit(ch.drop(columns = 'TARGET', axis =1 ), ch.TARGET)`

Error:
![image](https://user-images.githubusercontent.com/7208012/83787852-ff965880-a6c6-11ea-83a4-2561ff50bb4a.png)

(b) For Integer (dtype = int) without missing 
`params = {"I1": {"user_splits": [  0.,  1.,  2.,  4.,  3.,  5.,  6.,  9., 12.,  7.,  8.], 
                 "user_splits_fixed" : [True,True, True, True, True,True, True,True, True, True, True ]}}
optb = BinningProcess(['O1','O2','F1','I1'], categorical_variables=['O1','O2'], binning_fit_params  = params)

optb.fit(ch.drop(columns = 'TARGET', axis =1 ), ch.TARGET)`

Error:
![image](https://user-images.githubusercontent.com/7208012/83788447-c9a5a400-a6c7-11ea-8332-6f7e78488c4c.png)

(c) For object (dtype = object) 
with missing:
`params = {"I1": {"user_splits": [  '2.0', '5.0', '1.0', '4.0', '3.0', np.nan], 
                 "user_splits_fixed" : [True,True, True, True, True,True ]}}
optb = BinningProcess(['O1','O2','F1','I1'], categorical_variables=['O1','O2'], binning_fit_params  = params)

optb.fit(ch.drop(columns = 'TARGET', axis =1 ), ch.TARGET)`

Error: 
![image](https://user-images.githubusercontent.com/7208012/83788639-19846b00-a6c8-11ea-8f13-3e7b430ce6e8.png)


Attachment of sample data: 
[to_check.zip](https://github.com/guillermo-navas-palencia/optbinning/files/4731623/to_check.zip)

**Comment by guillermo-navas-palencia** [comment]
Ok, I will look into it. Note that adding np.nan in user_splits is not correct, np.nan is not a split or bin. A bin with nan will be automatically added if the datasets include missing values.

**Comment by similang** [comment]
Ya, you're right. Even after changing that I still hit errors.

**Comment by guillermo-navas-palencia** [comment]
Hi, 

Case a) 
```python
from optbinning import OptimalBinning

x = df["I1"]
y = df["TARGET"]

optb = OptimalBinning(user_splits=[1.,2.,3.,4.,5],
                      user_splits_fixed=[True, True, True, True, True])
optb.fit(x, y)
```
```python
optb.binning_table.build()
```
This will return no bins because the "auto" monotonicity constraint is activated.

![image](https://user-images.githubusercontent.com/40094942/83909120-7d5e7080-a768-11ea-89fe-98efbe1164c3.png)

Try:

```python
optb = OptimalBinning(user_splits=[1.,2.,3.,4.,5],
                      user_splits_fixed=[True, True, True, True, True],
                      monotonic_trend=None)
optb.fit(x, y)
```

```python
optb.binning_table.build()
```

![image](https://user-images.githubusercontent.com/40094942/83909221-b0086900-a768-11ea-9aa5-7e75f200e4ea.png)


Case b)

```python
optb = OptimalBinning(user_splits=[ 0., 1., 2., 4., 3., 5., 6., 9., 12., 7., 8.],
                      user_splits_fixed=[True,True, True, True, True,True, True,True, True, True, True])
```

This will return the following exception: This is due to the impossibility of computing the WoE and Information Value metric when the number of event or non-event records per bin is 0.

```
ValueError: Fixed user_splits [ 0. 12.  7.  8.] are removed because produce pure prebins. Provide different splits to be fixed.
``` 


Case c)

First, variable "I1" does not contain strings but numbers, therefore that error is justified. However, I have encountered a few errors when using ``user_splits_fixed`` and ``dtype="categorical"``. I will look into it. Note that categorical bins are list of list, for example: ``user_splits=[[2], [5], [1], [4], [3]]``.

The problem with ``BinningProcess`` is that it is not passing correctly the parameters ``user_splits`` and ``user_splits_fixed``. This is easy to fix.

Thanks, I will keep you posted.

**Comment by guillermo-navas-palencia** [comment]
Hi,

The current version in the master branch includes several bug fixes, and now it should work as expected.

Case a)

```python
params = {"I1": {"user_splits": [1.,2.,3.,4.,5],
                 "user_splits_fixed": [True, True, True, True, True]}}

binning_process = BinningProcess(variable_names=variable_names,
                                 categorical_variables=['O1', 'O2'],
                                 binning_fit_params=params)

binning_process.fit(df.drop(columns='TARGET', axis=1), df.TARGET)
```

```python
binning_process.summary()
```
![image](https://user-images.githubusercontent.com/40094942/83973533-5bd7c300-a8e7-11ea-92a0-2192cab15858.png)

Case b)

```python
params = {"I1": {"user_splits": [ 0., 1., 2., 4., 3., 5., 6., 9., 12., 7., 8.],
                 "user_splits_fixed": [True, True, True, True, True, True, True,
                                       True, True, True, True]}}

binning_process = BinningProcess(variable_names=variable_names,
                                 categorical_variables=['O1', 'O2'],
                                 binning_fit_params=params)

binning_process.fit(df.drop(columns='TARGET', axis=1), df.TARGET)
```

As above, this will return the following exception:
```
ValueError: Fixed user_splits [ 0. 12.  7.  8.] are removed because produce pure prebins. Provide different splits to be fixed.
```

Case c) In this example, the variable 'I1' is treated as nominal (categorical).

```python

params = {"I1": {"user_splits": [[2], [5], [1], [4], [3]],
                 "user_splits_fixed": [True, True, True, True, True]}}

binning_process = BinningProcess(variable_names=variable_names,
                                 categorical_variables=['I1', 'O1', 'O2'],
                                 binning_fit_params=params)

binning_process.fit(df.drop(columns='TARGET', axis=1), df.TARGET)
```

```python
binning_process.summary()
```
![image](https://user-images.githubusercontent.com/40094942/83973665-4c0cae80-a8e8-11ea-8a14-36274ec9843f.png)

Binning table:

```python
optb = binning_process.get_binned_variable("I1")
optb.binning_table.build()
```
![image](https://user-images.githubusercontent.com/40094942/83973725-97bf5800-a8e8-11ea-8b58-d38801013e30.png)

**Comment by guillermo-navas-palencia** [comment]
Version 0.6.1 is available with the discussed bug fixes.

Thanks for your feedback!

**Comment by similang** [comment]
Many thanks. By the way, I think you haven't add the plots for the plot options to remove bins which have 0 count right?

**Comment by guillermo-navas-palencia** [comment]
Options ``add_special`` and  ``add_missing`` are included. The default value is set to True. If you want to hide these bins from the plot, set ``add_special`` and/or  ``add_missing`` to False.

**Comment by similang** [comment]
Awesome! Many thanks.
