### ISSUE TITLE
Question On Custom Metric

### ISSUE THREAD

**Issue by thonig** [guillermo-navas-palencia/optbinning#43]
Hi,

thanks for sharing your project!

I'd like to do an optimal binning fit with a binary target and therefore have two rather specific questions:

1) Is it possible to optimize a custom metric?
Quick Example: If I declare S to be what you refer to as "Event" and B to be what you refer to as "Non-Event" i am looking for a binning that optimizes/maximizes e.g. S/(S+B) at a certain threshold.

2) If my values range from 0 to 1, I'd like to have the binning within [0,1] as well, rather than having the first bin starting from -inf and the last bin ranging to +inf. Is there a way to achieve this?

Cheers!

**Comment by guillermo-navas-palencia** [comment]
Hi,

1. Currently, the algorithm can only maximize the information value or Jeffrey's divergence, but other divergence metrics are suitable. I think your case would be to maximize the event rate of each optimal bin. Do you have a specific metric in mind? A custom metric would require significant changes in the underlying mathematical formulation, but I can study it if it is worth it.

2. The binning table method ``build`` returns a pandas dataframe, which can be customized as you like. I could, however, include an option to produce a table with initial bin [min(x), first split) and last bin [last split, max(x)] if it makes sense.

Best,
Guillermo

**Comment by guillermo-navas-palencia** [comment]
The parameter ``divergence`` was added in version 0.7.0:

The divergence measure in the objective function to be maximized. Supported divergences are “iv” (Information Value or Jeffrey’s divergence), “js” (Jensen-Shannon), “hellinger” (Hellinger divergence) and “triangular” (triangular discrimination).

**Comment by allan-araujo** [comment]
Hi, 

Is possible to add a another one? I would like to add the metric max(abs(dif( "accumulated event rate" -  "accumulated non-event rate"))) and optimize it. Is it possible? Thank you very mucj!

**Comment by guillermo-navas-palencia** [comment]
Hi @allan-araujo,

This seems the Kolmogorov-Smirnov (KS), but it should be the max(abs(accumulated count (%) event and accumulated count (%) non-event))? Is this would you mean? KS can be more difficult to implement, but I could try it.

**Comment by allan-araujo** [comment]
Hi, @guillermo-navas-palencia ,

 yes it's KS, you wrote it better. People in credit business like to use it as main metric for credit scoring. I think that it would be really nice to have.

Thank you very much!!!

**Comment by guillermo-navas-palencia** [comment]
Hi @allan-araujo,

I have implemented the mathematical formulation to maximize KS. In turns out that the KS obtained by maximizing the divergence measures IV and JS is the same, so the maximization of KS is implied. This was expected since the values of these divergences increase with the difference between the relative count of event and non-event. The formulation to maximize KS requires 7n + 1 (n number of bins) auxiliary constraints and 5n auxiliary decision variables, thus the CPU times are higher. Therefore, it is not necessary to provide this option. Note, however, that I included the KS value in the binning table analysis:

``` 
---------------------------------------------
OptimalBinning: Binary Binning Table Analysis
---------------------------------------------

  General metrics

    Gini index               0.15109253
    IV (Jeffrey)             0.07960977
    JS (Jensen-Shannon)      0.00990875
    Hellinger                0.00992992
    Triangular               0.03946728
    KS                       0.07054943
    HHI                      0.19451506
    HHI (normalized)         0.07944578
    Cramer's V               0.07866973
    Quality score            0.22796152

  Monotonic trend             ascending

  Significance tests

    Bin A  Bin B  t-statistic       p-value      P[A > B]  P[B > A]
        0      1     8.623744  3.318091e-03  1.439835e-03  0.998560
        1      2     1.406921  2.355682e-01  1.164286e-01  0.883571
        2      3   269.376110  1.551972e-60  2.904330e-97  1.000000
        3      4    23.618011  1.174827e-06  2.644030e-07  1.000000
        4      5    28.644991  8.693857e-08  4.370846e-12  1.000000
```

**Comment by allan-araujo** [comment]
Hi, @guillermo-navas-palencia. Thanks a million!!!
