### ISSUE TITLE
Qhull error

### ISSUE THREAD

**Issue by nic9lif3** [guillermo-navas-palencia/optbinning#48]
Hi @guillermo-navas-palencia 

I don't know extractly what this error means. Can you help me to explain it.
![image](https://user-images.githubusercontent.com/17736568/87774344-9b7ebc80-c84e-11ea-8367-646ef68f4dfb.png)

**Comment by guillermo-navas-palencia** [comment]
Hi @nic9lif3 

This is an error from the Qhull library in https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.ConvexHull.html. The convex hull is used to decide the monotonicity when ``monotonic_trend="auto"``, ``monotonic_trend="auto_heuristic"`` or ``monotonic_trend="auto_asc_desc"``. I will add a try/except to bypass this issue. In the meantime, you can use one of the non-auto monotonicity options. 

This will be corrected in version 0.7.0, to be released this month. Thanks for reporting it.

**Comment by guillermo-navas-palencia** [comment]
The version 0.7.0 with this bug fixe is available. Thanks!

**Comment by nic9lif3** [comment]
Thanks @guillermo-navas-palencia !
