### ISSUE TITLE
Result of monotonic_trend

### ISSUE THREAD

**Issue by nic9lif3** [guillermo-navas-palencia/optbinning#50]
Hi @guillermo-navas-palencia 

How I know what exactly trend of binning result that chosen by model when option monotonic_trend='auto'.

Thanks.

**Comment by guillermo-navas-palencia** [comment]
Hi @nic9lif3,

Currently, this information is not exposed to the user, but it can be added in the report returned by method ``.information()``. I will add it in the next release. For the time being, you can retrieve such information using: ``optb._optimizer.monotonic_trend``, where ``optb`` is a fitted Optimal Binning instance.

Thanks for the suggestion.

**Comment by nic9lif3** [comment]
Dear @guillermo-navas-palencia 

I found that in this situation of bad rate per bin, ```optb._optimizer.monotonic_trend=valley```. It is irrelevant because it look at bad rate of Missing bin and evaluate it is valley. I think monotinic trend is descending.
![image](https://user-images.githubusercontent.com/17736568/88891438-6b331700-d26d-11ea-8df8-3506705bc0ab.png)

**Comment by guillermo-navas-palencia** [comment]
Hi @nic9lif3,

The value of ``optb._optimizer.monotonic_trend`` is the monotonicity trend detected by the Machine Learning algorithm using data from pre-binning. This is not necessarily the monotonic trend of the optimal result. To clarify, the optimization process can replace valley/peak by descending/ascending if other constraints need to be satisfied (note that descending/ascending are particular cases of valley/peak).

Therefore, the final monotonic trend must be calculated after optimization, and this is what will be added in the next release.

**Comment by guillermo-navas-palencia** [comment]
Hi @nic9lif3,

The code in master includes the functionality to show the monotonic trend. This information is shown in ``opt.binning_table.analysis()``.

**Comment by nic9lif3** [comment]
Good news! thanks @guillermo-navas-palencia

**Comment by nic9lif3** [comment]
Does this version published in pypi @guillermo-navas-palencia ?

**Comment by guillermo-navas-palencia** [comment]
Hi @nic9lif3,

No, this change is only available in the master branch. To use it, you need to install optbinning from the source.

```
git clone https://github.com/guillermo-navas-palencia/optbinning.git
cd optbinning
python setup.py install
```

The next release, with this one and other updates, will be ready in September.
