### ISSUE TITLE
Monotonic trend on BinningProcess

### ISSUE THREAD

**Issue by billy-odera** [guillermo-navas-palencia/optbinning#52]
- How do I force the bins to have a monotonic trend when using **BinningProcess(variable_names, categorical_variables=categorical_variables,selection_criteria=selection_criteria)**
- I s there a way to round of the scores to the **nearest decimal place?**
- from the scorecard example how do i **fit the train data and not the entire dataset** as showing in the scoring tutorial scorecard.fit(df)

**Comment by guillermo-navas-palencia** [comment]
Hi @billy-odera,

1. You can pass particular options to some variables in the BinningProcess using parameter ``binning_fit_params``. For example, the following code will force monotonicity constraints to a few variables:

```python

binning_fit_params = {
    "ExternalRiskEstimate": {"monotonic_trend": "descending"},
    "MSinceOldestTradeOpen": {"monotonic_trend": "descending"},
    "MSinceMostRecentTradeOpen": {"monotonic_trend": "descending"},
    "AverageMInFile": {"monotonic_trend": "descending"},
    "NumSatisfactoryTrades": {"monotonic_trend": "descending"}
}
```
Then 

```
binning_process = BinningProcess(variable_names, categorical_variables=categorical_variables, selection_criteria=selection_criteria,
                                 binning_fit_params=binning_fit_params)
```

See complete example: http://gnpalencia.org/optbinning/tutorials/tutorial_binning_process_FICO_xAI.html

2. Yes, use parameter ``rounding`` in class Scorecard. Please read the documentation: http://gnpalencia.org/optbinning/scorecard.html

3. Use something like: ``df_train, df_test = train_test_split(df, test_size=0.2, random_state=42)``. Then, fit the scorecard with df_train, and run predict/predict_proba and score with df_test.

**Comment by billy-odera** [comment]
Thanks a lot really helpful
