### ISSUE TITLE
Assign missing class to a bin & BinningProcess with user splits

### ISSUE THREAD

**Issue by billy-odera** [guillermo-navas-palencia/optbinning#53]
I am running the below 
```
user_splits =  [2,6,14,24,34]
optb = OptimalBinning(name=variable, dtype="numerical", solver="mip",user_splits=user_splits)
optb.fit(x, y)
binning_table = optb.binning_table
binning_table.build()
```
that gives the below sample output
![image](https://user-images.githubusercontent.com/12785557/89458385-9dfa7500-d76f-11ea-95af-2e6364783d4d.png)
**How do I force the missing bin to be in bin 0?**

After running the user splits for the specific variables, how do I then use those splits when running the 
**binning_process = BinningProcess(variable_names, categorical_variables=categorical_variables, selection_criteria=selection_criteria)** fro the scorecard

**Comment by guillermo-navas-palencia** [comment]
Hi @billy-odera,

1. It is not possible to combine the missing bin with other bins. A missing bin is automatically generated if the dataset includes missing data. However, you can change the WoE value from -0.418329 to -0.0854013 when transforming using ``transform`` function in OptimalGrouping: http://gnpalencia.org/optbinning/binning_binary.html#optbinning.OptimalBinning.transform; use ``metric_missing= -0.0854013``.

2. You need to pass a dictionary with particular options via parameter ``binning_fit_params``. Example:

```python
binning_fit_params = {
    "variable": {"dtype": "numerical", "solver": "mip", "user_splits": [2,6,14,24,34]}
}

binning_process = BinningProcess(variable_names, categorical_variables=categorical_variables, 
                                 selection_criteria=selection_criteria, binning_fit_params=binning_fit_params)
```

**Comment by billy-odera** [comment]
Thanks for the feedback
