### ISSUE TITLE
Using class_weight parameter to BinningProcess

### ISSUE THREAD

**Issue by ds-mauri** [guillermo-navas-palencia/optbinning#54]
Hi @guillermo-navas-palencia !

Thanks for sharing your amazing work with the community.
It would be possible to use `class_weight` and `outlier_detector` as parameters to the BinningProcess class? I'm actually looping through the features using the OptimalBinning class. 

Thanks in advance!

**Comment by guillermo-navas-palencia** [comment]
Hi @ds-mauri,

To pass parameters for a particular variable to the BinningProcess, you can use parameter ``binning_fit_params``. For example:

```python
binning_fit_params = {
    "variable": {"class_weight": "balanced", "outlier_detector": "range" }
}

binning_process = BinningProcess(variable_names, binning_fit_params=binning_fit_params)
```

Similarly, you can construct a dictionary considering all variables or just a few of them. Let me know if it works for you!

**Comment by ds-mauri** [comment]
Thank you @guillermo-navas-palencia ! It surely helps.
