### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by billy-odera** [guillermo-navas-palencia/optbinning#55]
I am trying to run the scorecard model

```
scorecard_full = Scorecard(
    target='FLAG',
    binning_process=binning_process,
    estimator=lr,
    scaling_method=scaling_method,
    scaling_method_params=scaling_method_data,
    intercept_based=False,
    reverse_scorecard=False,
    rounding = True)
scorecard_full.fit(df_train)
```
but i get the below error 
`   Fitted scorecard.
           """
-->         return self._fit(df, metric_special, metric_missing, show_digits,
                             check_input)
AttributeError: 'DataFrame' object has no attribute 'dtype'`

my data frame has some missing values which i have not imputted

**Comment by guillermo-navas-palencia** [comment]
Hi @billy-odera,

Sorry, I have not encountered this issue before, but it looks like an input error. Could you share your data so I could try to reproduce the error?

Thanks!

**Comment by billy-odera** [comment]
yes sure,  advice on how I should send

**Comment by billy-odera** [comment]
I have figured out on what was the issue, I saved the the test and train dataset and imported them again
