### ISSUE TITLE
Missing values considered as Special on transform method

### ISSUE THREAD

**Issue by ds-mauri** [guillermo-navas-palencia/optbinning#58]
Hi, @guillermo-navas-palencia ! Again, thanks for sharing your work with the community 🥇

I was writing a class using the BinningProcess to create a binning table on a test dataset.  So, I have a df_train and a df_test, I fitted the BinningProcess using the df_train and transformed df_train and df_test. Then I checked the binning table. So far so good, the binning_table showed that I had some missing values in the Bin Missing, what is expected. 
After that I did a "safe check", I joined the df_train_transformed with the binning_table by WoE and re-grouped it by Bin. Then I realized that in the transformation, the BinningProcess was considering the Missing values as Special values, and it transformed it to WoE = 0. Am I doing something wrong in this process?

Steps to reproduce:

```python
# Get any DataFrame with missing values in column "feature_na"

binning_process = BinningProcess(variable_names=features,)

X_train, y_train = df_train.loc[:, features].copy(), df_train[target]

X_train_binned = binning_process.fit_transform(X_train, y_train)

# Check the WoE of each bin
binning_process.get_binned_variable(name='feature_na').binning_table.build()

# Check if these WoE are in the binned dataframe
X_train_binned.loc[:, 'feature_na'].unique()

# Or, for a more complex check, merge the X_train_binned with the binning_table on WoE and groupby Bin
```

**Comment by guillermo-navas-palencia** [comment]
Hi @ds-mauri,

In the docs you can read how to specify the strategy to handle missing and special values during data transformation:

![image](https://user-images.githubusercontent.com/40094942/90799243-3cabd780-e313-11ea-9574-1750dc428a4b.png)

In your particular case, you can use the option ``metric_missing="empirical"`` with ``fit_transform``. For your information, the situation where WoE = 0 can also happen if some values in df_train are not present in df_test, so the "neutral" WoE is assigned. Nonetheless, I will improve the documentation for the next release to clarify these cases. 

Let me know if that works for you!

**Comment by ds-mauri** [comment]
Thanks, @guillermo-navas-palencia . It worked perfectly!

I really didn't notice that it was the purpose of that parameter, my mistake. Thank you for the fast reply, though!
Just to clarify, what the parameter `check_input` would do?

Regards,

**Comment by guillermo-navas-palencia** [comment]
The parameter ``check_input`` does the following:

```python
# check X and y data
if check_input:
    X = check_array(X, ensure_2d=False, dtype=None,
                    force_all_finite='allow-nan')

    y = check_array(y, ensure_2d=False, dtype=None,
                    force_all_finite=True)

    check_consistent_length(X, y)
```
