### ISSUE TITLE
serializing the scorecard

### ISSUE THREAD

**Issue by mnjenga2** [guillermo-navas-palencia/optbinning#61]
Thank you for great work.
Kindly advise on how to serialize the scorecard function. 
I tried pickle, joblib and dill but they both give this error, "TypeError: cannot pickle 'SwigPyObject' object".
Thanks

**Comment by guillermo-navas-palencia** [comment]
Hi @mnjenga2,

I just implemented the methods save and load in the Scorecard class. See https://github.com/guillermo-navas-palencia/optbinning/commit/56d2c581e4fe722342260b5868fa843a1971e5af. This will be available in version 0.8.0 (mid-late September). In the meantime, you can install from source.

Best

**Comment by mnjenga2** [comment]
Thanks a lot
