### ISSUE TITLE
Problem with monotonic trend

### ISSUE THREAD

**Issue by nic9lif3** [guillermo-navas-palencia/optbinning#69]
Hi @guillermo-navas-palencia,

I see this problem when I try to set the value of the monotonic trend. When monotonic trend='descending', Optbinning will bin fail. On the other hands, with monotonic trend= 'auto' it's result will be like this:
![image](https://user-images.githubusercontent.com/17736568/102015407-0a285d80-3d8e-11eb-926b-52f184f1ad53.png)

I think this problem arises when the number of splits is 1.

**Comment by guillermo-navas-palencia** [comment]
Hi @nic9lif3,

Could you provide the data to reproduce the error?

Thank you

**Comment by nic9lif3** [comment]
Hi @guillermo-navas-palencia ,

Sorry, I can't provide this data for this problem. But I think maybe the problem occurs when the result  just has 1 split

**Comment by guillermo-navas-palencia** [comment]
Hi @nic9lif3,

Without data to reproduce the error, there is not much I can do. I will try what you suggested. Could you at least attach an image with the error?

Thanks

**Comment by guillermo-navas-palencia** [comment]
I have tested several cases with ``max_n_prebins=1`` and ``max_n_bins=1`` and the same with 2, and I did not encounter any issue.

**Comment by guillermo-navas-palencia** [comment]
Please reopen if you could provide more details. Thanks.
