### ISSUE TITLE
test data can't do binning_table build and plot

### ISSUE THREAD

**Issue by Spencerai** [guillermo-navas-palencia/optbinning#70]
In score card if we want to compare a variable results respectively in train and  test,we can not do woe or event_rate in test data.We can only do it in train data by`optb.binning_table.plot(metric='woe)`.Please add some function in test data?

**Comment by guillermo-navas-palencia** [comment]
Hi @Spencerai

I do not consider this requested feature very relevant at this stage of the development. Many modellers apply binning to the whole dataset before splitting the data for model training. However, you can create a binning table using the test data with the ``BinningTable`` class:  http://gnpalencia.org/optbinning/binning_tables.html.

If you would like to add extra functionalities, I welcome PRs.

Thanks,
Guillermo
