### ISSUE TITLE
scorecard.intercept_ did not work

### ISSUE THREAD

**Issue by rmokros** [guillermo-navas-palencia/optbinning#73]
Hey I'm on Ubuntu 20.04
python 3.8.5
--------
binning_process = BinningProcess(variable_names,binning_fit_params=({"solver":"mip"}),categorical_variables=variable_names, special_codes=special_codes,selection_criteria=selection_criteria)
estimator = LogisticRegression(solver="lbfgs")
scorecard = Scorecard(target='IBM', binning_process=binning_process,estimator=estimator,intercept_based=True)
scorecard.fit(data)
------

optbinning (Version 0.9.0)
Copyright (c) 2019-2021 Guillermo Navas-Palencia, Apache License 2.0

  Begin options
    target                               IBM   * U
    binning_process                      yes   * U
    estimator                            yes   * U
    scaling_method                        no   * d
    scaling_method_params                 no   * d
    intercept_based                     True   * U
    reverse_scorecard                  False   * d
    rounding                           False   * d
    verbose                            False   * d
  End options

  Statistics
    Number of records                   7299
    Number of variables                   20
    Target type                       binary

    Number of numerical                    0
    Number of categorical                 20
    Number of selected                     5

print(scorecard.intercept_ ) get ->  0

**Comment by guillermo-navas-palencia** [comment]
Hi @rmokros,

I would need the data to reproduce it. However, intercept_ can be 0 if the min score point for all variables is 0. Could you pass the data?

Kind regards

**Comment by rmokros** [comment]
I send the data by email  with the script 
[test.py.txt](https://github.com/guillermo-navas-palencia/optbinning/files/5822674/test.py.txt)


[test.gz](https://github.com/guillermo-navas-palencia/optbinning/files/5822676/test.gz)

**Comment by guillermo-navas-palencia** [comment]
Hi @rmokros,

The intercept_based option is only applied if  scaling_method is not None. I just checked that this is not included in the documentation. By default scaling_method is None, but you can choose either "min_max" or "pdo_odds".  For example:

```
scorecard = Scorecard(target='IBM', binning_process=binning_process, estimator=estimator,
                      scaling_method="min_max", scaling_method_params={"min": 300, "max": 850}, intercept_based=True)
```

OptBinning 0.10.0 will allow this option to be triggered when scaling_method is None.

Thanks for your feedback.

**Comment by guillermo-navas-palencia** [comment]
This option is now available in master.
