### ISSUE TITLE
Scorcard

### ISSUE THREAD

**Issue by rmokros** [guillermo-navas-palencia/optbinning#74]
Is there any way that I don't get  Special and Missing bins into the Scorecard,  how can I get rid of features that have more than 50% of the population. 
The last question (for this post)  how can I made the bin's integer. The feature has NaN this means datatype si float, but the bins are elements (ints), and I get [1.5, 2.5) which means  2 in this range

**Comment by guillermo-navas-palencia** [comment]
Hi @rmokros,

1. The special and missing bins are always included.
2. To exclude features with special and/or missing > 50%, you should implement a preprocessing step.
3. Correct. Using floats is more conservative in case data might include floats in the future.

The general idea is that the scorecard should be applicable to new datasets (let's consider that it was developed with data collected until 2019, and we want to evaluate it with data from 2020) which might include special, NaNs or might change the data type for a particular variable.
