### ISSUE TITLE
Gini results

### ISSUE THREAD

**Issue by naenumtou** [guillermo-navas-palencia/optbinning#84]
Hi,

When I apply data with `BinningProcess`. The results were given negative and more than 1.
However, I tried to recalculate WOE and IV, the results are matched with the results from library.
What is the cause of these negative GINI? 

![image](https://user-images.githubusercontent.com/66057952/108507976-b0906200-72ed-11eb-9fb4-f71857ad397b.png)

**Comment by guillermo-navas-palencia** [comment]
Hi @naenumtou,

First time I see this error. Could you provide the data to replicate it or screenshots of the binning table (.build() and .analysis()) for each variable?

Thanks

**Comment by naenumtou** [comment]
@guillermo-navas-palencia Thanks for the responding.

I have added 'grade' variable's details from .build() and .analysis() as below. Due to data size limited on the comment, you can find the data I have used as Google Drive.

https://drive.google.com/file/d/1SYwrNr64FVZuizMDnJGDkpdElgEH4f-J/view?usp=sharing

![image](https://user-images.githubusercontent.com/66057952/108598463-590ef680-73c0-11eb-9531-56539e44ce4a.png)

![image](https://user-images.githubusercontent.com/66057952/108598470-61ffc800-73c0-11eb-8004-eaf86bf583bc.png)

**Comment by guillermo-navas-palencia** [comment]
Hi @naenumtou,

Thanks for providing the whole dataset. I tested the binning process and I did not encounter any problem. See screenshots:

![image](https://user-images.githubusercontent.com/40094942/108602034-25bc6f80-73a0-11eb-8f9e-905443b84778.png)

![image](https://user-images.githubusercontent.com/40094942/108602041-2fde6e00-73a0-11eb-8384-c77445a2b479.png)

![image](https://user-images.githubusercontent.com/40094942/108602054-3c62c680-73a0-11eb-9afd-7f2346615045.png)

Could you specify your OS (32 or 64 bits?) and Python version?

**Comment by guillermo-navas-palencia** [comment]
The only thing that comes to mind is an issue with large integers in the following code:

```python
def gini(event, nonevent):
    """Calculate the Gini coefficient given the number of events and
    non-events.

    Parameters
    ----------
    event : array-like
        Number of events.

    nonevent : array-like
        Number of non-events.

    Returns
    -------
    gini : float
    """
    event, nonevent = _check_x_y(event, nonevent)

    mask = (event + nonevent) > 0
    event = event[mask]
    nonevent = nonevent[mask]

    n = len(event)
    if n <= 1:
        return 0
    else:
        te = event.sum()
        tne = nonevent.sum()

        ner = nonevent / (event + nonevent)
        idx = np.argsort(ner)
        ev = event[idx]
        ne = nonevent[idx]

        s = np.zeros(n)
        s[1:] = 2.0 * ne[:-1].cumsum()

        return 1.0 - np.dot(ev, ne + s) / (te * the)
```

**Comment by naenumtou** [comment]
@guillermo-navas-palencia Thanks for reaching out.

I think the problem is come with numpy because I got the warning log during using `BinningProcess` as below.

```
RuntimeWarning: overflow encountered in long_scalars
  return 1.0 - np.dot(ev, ne + s) / (te * tne)
```

Currently, I am using python version 3.7.9 and numpy version 1.20.1

**Comment by guillermo-navas-palencia** [comment]
I think the problem is due to numpy using int32 instead of int64 in your platform. Could you try the following code where int arrays are cast as floats?

```python
def gini(event, nonevent):
    """Calculate the Gini coefficient given the number of events and
    non-events.

    Parameters
    ----------
    event : array-like
        Number of events.

    nonevent : array-like
        Number of non-events.

    Returns
    -------
    gini : float
    """
    event, nonevent = _check_x_y(event, nonevent)

    mask = (event + nonevent) > 0
    event = event[mask].astype(np.float)
    nonevent = nonevent[mask].astype(np.float)

    n = len(event)
    if n <= 1:
        return 0
    else:
        te = event.sum()
        tne = nonevent.sum()
        
        print(type(te))

        ner = nonevent / (event + nonevent)
        idx = np.argsort(ner)
        ev = event[idx]
        ne = nonevent[idx]

        s = np.zeros(n)
        s[1:] = 2.0 * ne[:-1].cumsum()

        return 1.0 - np.dot(ev, ne + s) / (te * tne)
```

**Comment by guillermo-navas-palencia** [comment]
I will change the implementation to avoid large divisions:

```python
        ev = event[idx] / te
        ne = nonevent[idx] / tne

        s = np.zeros(n)
        s[1:] = 2.0 * ne[:-1].cumsum()
```

**Comment by guillermo-navas-palencia** [comment]
Please install from source using the code in the branch develop. Reopen this issue if needed.

**Comment by naenumtou** [comment]
@guillermo-navas-palencia I have tried to change type to float, it's work fine with correct GINI results.

I would suggest that you don't need to avoid large division by divided with `te` and `tne`. It leads to wrong GINI results.

**Comment by guillermo-navas-palencia** [comment]
Does the following code fail in your environment? I run unit tests without differences:

```python
def gini(event, nonevent):
    """Calculate the Gini coefficient given the number of events and
    non-events.

    Parameters
    ----------
    event : array-like
        Number of events.

    nonevent : array-like
        Number of non-events.

    Returns
    -------
    gini : float
    """
    event, nonevent = _check_x_y(event, nonevent)

    mask = (event + nonevent) > 0
    event = event[mask]
    nonevent = nonevent[mask]

    n = len(event)
    if n <= 1:
        return 0
    else:
        te = event.sum()
        tne = nonevent.sum()

        ner = nonevent / (event + nonevent)
        idx = np.argsort(ner)
        ev = event[idx] / te
        ne = nonevent[idx] / tne

        s = np.zeros(n)
        s[1:] = 2.0 * ne[:-1].cumsum()

        return 1.0 - np.dot(ev, ne + s)
```

**Comment by naenumtou** [comment]
@guillermo-navas-palencia  Yes, it fail with my environment.

I noticed that when I added `/ te` and `/ tne`, the results returned as `1`. However, when I changed data type of `event` and `nonevent` to `np.float` **without** `/ te` and `/ tne`, the gini results are correct.

**Comment by guillermo-navas-palencia** [comment]
@naenumtou understood. I will keep the version casting event and nonevent to floats.
