### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by yssefunc** [guillermo-navas-palencia/optbinning#85]
Hello,
I am getting the error "ImportError: numpy.core.multiarray failed to import" when you run the code below,
```
 from optbinning import OptimalBinning
 optb = OptimalBinning(name=variable, dtype="numerical", solver="cp")
 optb.fit(x, y)
```
I did some research on the Internet. It is related to NumPy version. My NumPy version is 1.19.1. Thus, I downgraded NumPy versions 1.18 and then, 1.17. But, I am still getting the error.

**Comment by guillermo-navas-palencia** [comment]
Hi @yssefunc,

This error is common with NumPy, as you mentioned. I would advise you to create a virtual environment with python >= 3.7 or trying to make sure that all old versions of NumPy were uninstalled. See https://github.com/tensorflow/tensorflow/issues/559.

**Comment by yssefunc** [comment]
Hello @guillermo-navas-palencia,

Thank you for your quick response. I create a virtual environment. Then, I did "pip install NumPy --upgrade". Now, it works. 

Thanks again,

**Comment by guillermo-navas-palencia** [comment]
You are welcome. I close this issue.
