### ISSUE TITLE
Question on scorecard.table(style="detailed")

### ISSUE THREAD

**Issue by rmokros** [guillermo-navas-palencia/optbinning#87]
Still not understanding the whole idea.
I have 6 ranges, this will be mapped to an onehot encoding, then they should have a different Coefficient.
If this feature is modeled as continues why do we have the bins? 
And last what does the Points column mean? 

> scorecard = Scorecard(target='IndByM', binning_process=binning_process,
>                       estimator=estimator, scaling_method="min_max",
>                       scaling_method_params={"min": 0, "max": 1000},
>                       intercept_based=True)

![image](https://user-images.githubusercontent.com/24894309/110177086-666dad00-7dd2-11eb-831d-3baa4d1aba6a.png)

**Comment by guillermo-navas-palencia** [comment]
Hi @rmokros,

This is how scorecard modelling works. Considering a binary target:

1. Replace continuous and categorical variables with WoE
2. For each variable, the column points is the WoE multiplied by the corresponding coefficient return by the estimator, a logistic regression, for instance.
3. The same coefficient for all bins of a variable, but different points.
4. The score is computed using the Points columns.

See how scorecards are implemented in other software:

- https://documentation.sas.com/?docsetId=emref&docsetTarget=n181vl3wdwn89mn1pfpqm3w6oaz5.htm&docsetVersion=14.3&locale=en
- https://es.mathworks.com/help/finance/credit-scorecard-modeling-workflow.html
