### ISSUE TITLE
VisibleDeprecationWarning

### ISSUE THREAD

**Issue by shivtrig** [guillermo-navas-palencia/optbinning#90]
Hi @guillermo-navas-palencia, 

It shows me a VisibleDeprecationWarning when I try to specify the user_splits for a categorcial variable of integer type. Say for eg: - I have month as the categorical variable and it's of integer type ranging from 1 to 12. 
When I want specific splits, say combine month 1 & 2 in one bin, 3 & 4 in another bin and try to fit the binning_process, it shows me the below warning: 

![image](https://user-images.githubusercontent.com/53851584/111027785-727fed00-8418-11eb-9f78-27876caa9274.png)

Code:

```
features = ['Month']
X = data[features]
y = data['target'].values

user_splits_month = [[1,2],
               [3,4],
               [5],
               [6],
               [7],
               [8],
               [9],
               [10],
              [11],
               [12]]

categorical_variables = ['Month']

binning_fit_params = {"Month":{"user_splits":user_splits_month}}
binning_fit_params

binning_process = BinningProcess(features,categorical_variables=categorical_variables,binning_fit_params=binning_fit_params)
binning_process.fit(X, y)
```

Is this expected? May I know why this warning pops up?

**Comment by guillermo-navas-palencia** [comment]
Hi @shivtrig,

This is a new deprecation warning from NumPy (starting from numpy>=1.2.0). I have amended most of them in the lastest release (0.9.2), but I missed this one. I will add the dtype="object", but I should not have any effect at this moment.

**Comment by guillermo-navas-palencia** [comment]
https://github.com/guillermo-navas-palencia/optbinning/commit/944fef57e1013f1ad8921d1522321791c2d229e5

**Comment by shivtrig** [comment]
@guillermo-navas-palencia Thank you! I will check it out and let you know.
