### ISSUE TITLE
More bins returned than `max_n_bins`

### ISSUE THREAD

**Issue by timvink** [guillermo-navas-palencia/optbinning#91]
First of all kudos for the amazing package and the enormous amount of work that you must have put into it. Really cool stuff, thanks!

I found a situtation where `OptimalBinning` occasionally returns more bins than `max_n_bins`:
 
```python
import random
import numpy as np
import pandas as pd
from optbinning import OptimalBinning
from sklearn.datasets import load_breast_cancer
from sklearn.exceptions import NotFittedError

data = load_breast_cancer()
df = pd.DataFrame(data.data, columns=data.feature_names)
y = data.target

# Normal binning of numerical
optb = OptimalBinning(max_n_bins=2, dtype='numerical')
len(np.unique(optb.fit_transform(df["mean radius"].values, y)))
#> 2

# Add fake categorical
pets = ["no pets"] * 77 + ["cat lover"] * 93 + ["dog lover"] * 143 + ["rabbit"] * 134 + ["gold fish"] * 122
random.Random(42).shuffle(pets)
df['pets'] = pets

# Normal binning of categorical
optb = OptimalBinning(max_n_bins=2, dtype='categorical')
len(np.unique(optb.fit_transform( df['pets'].values, y)))
#> 2

# However, in combination with cat_cutoff, max_bins can be higher:
optb = OptimalBinning(max_n_bins=2, dtype='categorical', cat_cutoff=0.2,)
len(np.unique(optb.fit_transform(x, y)))
#> 3

# With lower `cat_cutoff`, it's OK again.
optb = OptimalBinning(max_n_bins=2, dtype='categorical', cat_cutoff=0.1,)
len(np.unique(optb.fit_transform(x, y)))
# 2
```

I'm using `optbinning==0.9.2`, python `3.8.3` on macOS.

**Comment by guillermo-navas-palencia** [comment]
Hi @timvink,

Glad you find it useful! Regarding your question:

- The maximum number of bins does not count the special and missing bin. These two bins are always included by default.
- For categorical variables, the other bin that might be generated by cat_cutoff is not included in max_bins, it is treated as another special bin that cannot be merged. For example,  

```python
optb = OptimalBinning(max_n_bins=2, dtype='categorical', cat_cutoff=0.2)
optb.fit(df['pets'].values, y)
```
This produces the following binning table:
```python
optb.binning_table.build()
```
![image](https://user-images.githubusercontent.com/40094942/112621181-bbc53900-8e29-11eb-8525-36dd4d66f063.png)

if you plot the binning result, you can detect the other bin by the lighter colour of the third bin. If you discount the other bin, then you have 2 bins as enforced using ``max_bins=2``. 

![image](https://user-images.githubusercontent.com/40094942/112621492-1a8ab280-8e2a-11eb-9f23-b256736a39dd.png)

I will add clarification in the docs with the next release 0.10.0.

Regards,
Guillermo

**Comment by timvink** [comment]
Not a bug, a feature! Thanks for the clarification :)
