### ISSUE TITLE
useing multiclass binning but can only get one bin

### ISSUE THREAD

**Issue by Cuilinxiao** [guillermo-navas-palencia/optbinning#94]
I'm useing the wine dataset in sklearn，I want to bin the continuous feature 'od280/od315_of_diluted_wines' ,there are three wine classes, so i use the MulticlassOptimalBinning(), but the result is very weird,  there is only one bin, when i bin other continuous features like 'malic_acid' result is quite normal. 
can somebody help, thanks

![微信图片_20210424180624](https://user-images.githubusercontent.com/58239943/115962228-e1d71980-a54c-11eb-9dd9-7a06449d299e.png)
![微信图片_20210424180631](https://user-images.githubusercontent.com/58239943/115962234-e4397380-a54c-11eb-853f-d823a049564d.png)

**Comment by guillermo-navas-palencia** [comment]
Hi @Cuilinxiao,

For this particular variable, the underlying decision tree is not able to compute prebins such that all event columns are > 0. The solver requires these columns to be positive to compute the divergence measure (Jensen-Shannon) to be optimized. For small datasets, this situation is not unusual. To see more about the reason, use verbose=True when instantiating the MulticlassOptimalBinning class:

![image](https://user-images.githubusercontent.com/40094942/115968488-7d11c400-a538-11eb-893d-e84eb0fc2c52.png)

As mentioned, the solver optimizes the Jensen-Shannon divergence. You can see these statistis using the method ``binning_table.analysis()``:

![image](https://user-images.githubusercontent.com/40094942/115968527-aa5e7200-a538-11eb-82de-be2d707203cc.png)

Let me know if anything is unclear.

**Comment by Cuilinxiao** [comment]
thanks a lot,  i still have some questions, the prebin method is the cart tree, so i traind a tree use the feature 'od280/od315_of_diluted_wines', and in the first split , the classes count in left node only contains two classes, does this cause it unable to prebin? 
![图片](https://user-images.githubusercontent.com/58239943/115982505-530ae100-a5ce-11eb-9d7a-f3be2b65f1ab.png)


and why the count of this bin is 356, there are only 178 samples
![图片](https://user-images.githubusercontent.com/58239943/115982508-5b631c00-a5ce-11eb-8ad7-c6f861c24b98.png)

thanks

**Comment by guillermo-navas-palencia** [comment]
Hi @Cuilinxiao. Indeed, I did not notice the error in Count. This is odd, I will look into this.

**Comment by guillermo-navas-palencia** [comment]
Thanks. It was a bug when the decision tree is not able to create split points. It is fixed in the develop branch.

**Comment by Cuilinxiao** [comment]
Thanks @guillermo-navas-palencia
I'm quite new in this aera, actually, I dont know what is prebin and why prebin is necessary. It sounds to me that, to bin the feature 'od280/od315_of_diluted_wines' with supervision,  just need traverse each data point in 'od280/od315_of_diluted_wines' ,and use each point as a split point, and calculate the entrophy in each bin,  use the splits which can get the minimum entrophy.

**Comment by guillermo-navas-palencia** [comment]
The algorithm implemented in OptBinning computes a set of prebins using a decision tree algorithm, and solves an optimization problem to satisfy user's constraints, thus obtaining the actual optimal bins. The goal is to maximize divergence, i.e., the difference between bins. More information: http://arxiv.org/abs/2001.08025

The bugfix is now part of the master branch. You can install from source to get the correct results.
