### ISSUE TITLE
Save optimal binning object in JSON format

### ISSUE THREAD

**Issue by guillermo-navas-palencia** [guillermo-navas-palencia/optbinning#96]
1. Save optimal bins and/or splits points and transformation depending on the target type.
2. This is handy to implement binning transformation with other languages (e.g., SAS). Only a JSON parser is required to produce a set of if-else to transform original data.
3. Read JSON as a class method.

**Comment by alexliap** [comment]
When saving the splits and transformation, should the metric for transform be 'woe', 'event_rate', 'bins' or 'indices'?
